In [1]:
from pathlib import Path

CUAD_ROOT = Path("/kaggle/input/datasets/riyasuryawanshi/cuad-project")
SCAN_ROOT = Path("/kaggle/input/datasets/riyasuryawanshi/scan-vs-span")

print("CUAD project:", CUAD_ROOT.exists())
print("Indian set:", (CUAD_ROOT / "indian_set").exists())
print("Scan-vs-span:", SCAN_ROOT.exists())

for name in [
    "train_phase3.py",
    "scan_vs_span.py",
    "model.py",
    "dataset.py",
    "metrics.py",
    "ckpt_joint_cls_span_fold0.pt",
    "partial/config.json",
]:
    print(f"{name}: {(SCAN_ROOT / name).exists()}")

print("Indian evaluator:",
      (CUAD_ROOT / "indian_set" / "eval_indian.py").exists())
print("Indian builder:",
      (CUAD_ROOT / "indian_set" / "build_indian_testset.py").exists())

CUAD project: True
Indian set: True
Scan-vs-span: True
train_phase3.py: True
scan_vs_span.py: True
model.py: True
dataset.py: True
metrics.py: True
ckpt_joint_cls_span_fold0.pt: True
partial/config.json: True
Indian evaluator: True
Indian builder: True

In [2]:
from pathlib import Path
import shutil
import os

WORK = Path("/kaggle/working/indian_eval_project")

if WORK.exists():
    shutil.rmtree(WORK)

shutil.copytree(SCAN_ROOT, WORK)

print("Working copy created:", WORK)
print("train_phase3.py:", (WORK / "train_phase3.py").exists())
print("scan_vs_span.py:", (WORK / "scan_vs_span.py").exists())
print("Checkpoint:", (WORK / "ckpt_joint_cls_span_fold0.pt").exists())
print("Config:", (WORK / "partial/config.json").exists())

Working copy created: /kaggle/working/indian_eval_project
train_phase3.py: True
scan_vs_span.py: True
Checkpoint: True
Config: True

In [3]:
from pathlib import Path
import shutil

src = CUAD_ROOT / "indian_set"
dst = WORK / "indian_set"

assert src.exists(), f"Indian set not found: {src}"

if dst.exists():
    shutil.rmtree(dst)

shutil.copytree(src, dst)

print("Indian set copied:", dst)
print("Documents folder:", (dst / "documents").exists())
print("Builder:", (dst / "build_indian_testset.py").exists())
print("Evaluator:", (dst / "eval_indian.py").exists())

print("\nFiles copied:")
for p in sorted(dst.iterdir()):
    print(p.name)

Indian set copied: /kaggle/working/indian_eval_project/indian_set
Documents folder: False
Builder: True
Evaluator: True

Files copied:
aera_rfp_consultant_2025.txt
build_indian_testset.py
clause_browser.csv
documents_manifest.csv
dot_unified_licence_agreement.txt
eval_indian.py
gem_general_terms_and_conditions.txt
himachal_hemodialysis_ppp_concession_agreement.txt
mea_architect_consultancy_agreement.txt
mea_pmc_services_agreement.txt
meity_msa_cloud_services_template.txt
mha_rfp_project_management_consultants.txt
noida_airport_concession_agreement.txt
prepare_documents.py
smoke_test.py
stqc_non_disclosure_agreement.txt
tender_consultancy_scc_1349.txt

In [4]:
from pathlib import Path
import shutil

indian = WORK / "indian_set"
docs_dir = indian / "documents"
docs_dir.mkdir(exist_ok=True)

# Copy only agreement text files into documents/
txt_files = list(indian.glob("*.txt"))

for src in txt_files:
    shutil.copy2(src, docs_dir / src.name)

print("Documents copied:", len(list(docs_dir.glob("*.txt"))))
print("\nFiles:")
for p in sorted(docs_dir.glob("*.txt")):
    print(p.name, "-", p.stat().st_size, "bytes")

Documents copied: 11

Files:
aera_rfp_consultant_2025.txt - 117936 bytes
dot_unified_licence_agreement.txt - 357403 bytes
gem_general_terms_and_conditions.txt - 75017 bytes
himachal_hemodialysis_ppp_concession_agreement.txt - 201172 bytes
mea_architect_consultancy_agreement.txt - 24286 bytes
mea_pmc_services_agreement.txt - 23618 bytes
meity_msa_cloud_services_template.txt - 107511 bytes
mha_rfp_project_management_consultants.txt - 87392 bytes
noida_airport_concession_agreement.txt - 769972 bytes
stqc_non_disclosure_agreement.txt - 15055 bytes
tender_consultancy_scc_1349.txt - 9756 bytes

In [6]:
from pathlib import Path
import csv

indian = WORK / "indian_set"
clauses_file = indian / "clauses.csv"

with clauses_file.open("w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow([
        "document_file",
        "category",
        "clause_text",
        "source_note"
    ])

print("Created:", clauses_file)
print("Columns:", next(csv.reader(
    clauses_file.open(encoding="utf-8")
)))

Created: /kaggle/working/indian_eval_project/indian_set/clauses.csv
Columns: ['document_file', 'category', 'clause_text', 'source_note']

In [7]:
from pathlib import Path

doc_path = WORK / "indian_set" / "documents" / "aera_rfp_consultant_2025.txt"
text = doc_path.read_text(encoding="utf-8", errors="replace")

print("Document:", doc_path.name)
print("Characters:", len(text))

for term in ["Confidentiality", "Indemnification"]:
    print(f"\n{term}:")
    start = text.lower().find(term.lower())
    if start == -1:
        print("Not found")
    else:
        print(text[max(0, start-100):start+500])

Document: aera_rfp_consultant_2025.txt
Characters: 117602

Confidentiality:
ification and post-qualification experience as requested in bid document.

3. I shall maintain full confidentiality with respect to the material, information, document, etc. as may be made available to me during the proposed assignment.

(Signature and name of the Key Personnel)

(Signature, name and designation) Duly authorized to sign for and on behalf of bidder Seal of the Bidder

Note:

1. Use separate form for each Key Personnel.

2. This form to be signed by respective Key Personnel and the Authorized Signatory of the Bidder.

Form – 4

Assignment Details of the Bidder

S. No.

Details o

Indemnification:
Not found

In [8]:
import re

doc_path = WORK / "indian_set" / "documents" / "aera_rfp_consultant_2025.txt"
text = doc_path.read_text(encoding="utf-8", errors="replace")

for term in ["confidential", "indemnif", "hold harmless"]:
    matches = list(re.finditer(term, text, re.IGNORECASE))
    print(f"\n{term!r}: {len(matches)} matches")

    for m in matches[:5]:
        start = max(0, m.start() - 150)
        end = min(len(text), m.end() + 350)
        print("-" * 50)
        print(text[start:end].replace("\n", " "))

'confidential': 13 matches
--------------------------------------------------
resented. Further, I have requisite essential qualification and post-qualification experience as requested in bid document.  3. I shall maintain full confidentiality with respect to the material, information, document, etc. as may be made available to me during the proposed assignment.  (Signature and name of the Key Personnel)  (Signature, name and designation) Duly authorized to sign for and on behalf of bidder Seal of the Bidder  Note:  1. Use separate form for each Key Personnel.  2. This form to be sig
--------------------------------------------------
pplicable Laws” means the laws and any other instruments having the force of law in India as they may be issued and in force from time to time;  d)  “Confidential Information” shall have the meaning set forth in Clause 3.3;  e)  “Conflict of Interest” shall have the meaning set forth in Clause 3.2 read with the provisions of  RFP;  f)  “Dispute” shall have the meaning set forth in Clause 9;  g)  “Effective Date” means the date on which this Agreement comes into force and effect pursuant to Clause 2.1;  h)
--------------------------------------------------
ts and obligations as may have accrued on the date of termination or expiration, or which expressly survives such Termination; (ii) the obligation of confidentiality set forth in Clause 3.3 hereof; (iii) any right or remedy which a Party may have under this Agreement or the Applicable Laws.  2.10.4  Cessation of Services Upon termination of this Agreement by notice of either Party to the other pursuant to Clauses 2.10.1 or  2.10.2 hereof, the Consultant shall, immediately upon dispatch or receipt of such no
--------------------------------------------------
y understanding or arrangement among Bidders with the objective of restricting or manipulating a full and fair competition in the Selection Process.  Confidentiality The Consultant and its Key Personnel shall not, either during the term or within one year after the expiration or termination of this Agreement disclose any proprietary information, including information relating to reports, data, drawings, design software or other material, whether written or oral, in electronic or magnetic format, and the con
--------------------------------------------------
professionals or suppliers, customers, or contractors of the Authority; and any other information which the Consultant is under an obligation to keep confidential in relation to the Project, the Services or this Agreement ("Confidential Information"), without the prior written consent of the Authority.  Notwithstanding the aforesaid, the Consultant, its Key Personnel or either of them may disclose, with prior written approval of the Authority, Confidential Information to the extent that such Confidential In

'indemnif': 2 matches
--------------------------------------------------
poses not related to this Agreement without the prior written approval of the Authority.  3.6.4  The Consultant shall hold the Authority harmless and indemnified for any losses, claims, damages, expenses (including all legal expenses), awards, penalties or injuries (collectively referred to as “Claims”) which may arise from or due to any unauthorized use of such Consultancy Documents, or due to any breach or failure on part of the Consultant (or any Third Party appointed by the Consultant) to perform an
--------------------------------------------------
er agencies/ authorities, estimates and all other details prepared by it as part of these services. Subject to the provisions of Clause 3.4, it shall indemnify the Authority against any inaccuracy in its work which might surface during the currency of the assignment [i.e., till completion of milestone/ activity 4 as given in clause 2.4(d) of the RFP], if such inaccuracy is the result of any negligence or inadequate due diligence on part of the Consultant or arises out of its failure to conform to good i

'hold harmless': 0 matches

In [9]:
from pathlib import Path
import csv
import re

indian = WORK / "indian_set"
doc_name = "aera_rfp_consultant_2025.txt"
doc_path = indian / "documents" / doc_name
text = doc_path.read_text(encoding="utf-8", errors="replace")

# Find the Confidentiality heading anywhere in the document
conf_match = re.search(r"Confidentiality\s+The Consultant and its Key Personnel", text, re.I)
if not conf_match:
    raise ValueError("Could not locate the Confidentiality clause.")

conf_start = conf_match.start()
conf_end_match = re.search(r"\n\s*(?:3\.\d+(?:\.\d+)?\s+|4\.\d+(?:\.\d+)?\s+)", text[conf_match.end():])
conf_end = conf_match.end() + conf_end_match.start() if conf_end_match else conf_match.end() + 5000
conf_clause = text[conf_start:conf_end].strip()

# Find Indemnification clause 3.6.4
ind_match = re.search(r"3\.6\.4\s+The Consultant shall hold the Authority", text, re.I)
if not ind_match:
    raise ValueError("Could not locate clause 3.6.4.")

ind_next = re.search(r"3\.6\.5\b", text[ind_match.end():])
ind_end = ind_match.end() + ind_next.start() if ind_next else min(len(text), ind_match.end() + 3000)
ind_clause = text[ind_match.start():ind_end].strip()

rows = [
    [doc_name, "Confidentiality", conf_clause, "AERA agreement; Confidentiality section"],
    [doc_name, "Indemnification", ind_clause, "AERA agreement; clause 3.6.4"],
]

out = indian / "clauses.csv"
with out.open("w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["document_file", "category", "clause_text", "source_note"])
    writer.writerows(rows)

print("Saved:", out)
print("Annotations:", len(rows))
print("Confidentiality characters:", len(conf_clause))
print("Indemnification characters:", len(ind_clause))
print("Confidentiality exact source match:", conf_clause in text)
print("Indemnification exact source match:", ind_clause in text)

Saved: /kaggle/working/indian_eval_project/indian_set/clauses.csv
Annotations: 2
Confidentiality characters: 2523
Indemnification characters: 3046
Confidentiality exact source match: True
Indemnification exact source match: True

In [11]:
import subprocess
import sys
import os

builder = WORK / "indian_set" / "build_indian_testset.py"

env = os.environ.copy()
env["PYTHONPATH"] = (
    str(WORK) + os.pathsep +
    str(WORK / "indian_set") + os.pathsep +
    env.get("PYTHONPATH", "")
)

result = subprocess.run(
    [sys.executable, str(builder), "--help"],
    capture_output=True,
    text=True,
    cwd=str(WORK),
    env=env
)

print("Return code:", result.returncode)
print(result.stdout)
if result.stderr:
    print("STDERR:", result.stderr)

Return code: 0
usage: build_indian_testset.py [-h] [--docs_dir DOCS_DIR]
                               [--clauses_csv CLAUSES_CSV] [--out_dir OUT_DIR]
                               [--make_template DIR] [--list_categories]

build_indian_testset.py -- turn your hand-collected Indian clauses into a test set
the Phase 3 code can evaluate.

YOU PROVIDE
    indian_set/documents/*.txt   full plain text of each Indian agreement / template
    indian_set/clauses.csv       one row per clause you picked
        document_file   file name inside documents/ (e.g. nda_sample_1.txt)
        category        one of the 18 ClauseXplain categories (exact spelling, see --list_categories)
        clause_text     the clause, COPIED from that document (whitespace differences are fine)
        source_note     where the document came from (public template, tender, ...)

THIS SCRIPT
    finds each clause inside its document (so we get exact character offsets, which
    the span evaluation needs), and writes
        built/indian_mapped.jsonl      same format as clauses_mapped.jsonl
        built/indian_contracts.json    {contract_id: full text}
        built/build_report.md          counts, problems, coverage warnings

    python build_indian_testset.py --make_template indian_set      # starter folder + CSV
    python build_indian_testset.py --docs_dir indian_set/documents --clauses_csv indian_set/clauses.csv --out_dir indian_set/built

GUIDANCE FOR COLLECTING (so the set is honest)
    * Use documents you are allowed to use (public templates, government tender
      documents, sample agreements). Do not include confidential or personal data.
    * Pick clauses by CATEGORY MEANING, before looking at what any model predicts.
    * Aim for 3+ clauses per category you can cover, 30-50 in total, from several
      different documents.  Some categories (Confidentiality, Indemnification,
      Payment, Force Majeure, Modification, Privacy) are valuable to include: the
      model has never seen them, and the report will say so.
    * If a clause could fit two categories, choose the closest and add a source_note.

options:
  -h, --help            show this help message and exit
  --docs_dir DOCS_DIR
  --clauses_csv CLAUSES_CSV
  --out_dir OUT_DIR
  --make_template DIR   create DIR/documents and DIR/clauses.csv
  --list_categories

In [12]:
import subprocess
import sys
import os

env = os.environ.copy()
env["PYTHONPATH"] = (
    str(WORK) + os.pathsep +
    str(WORK / "indian_set") + os.pathsep +
    env.get("PYTHONPATH", "")
)

result = subprocess.run(
    [
        sys.executable,
        str(WORK / "indian_set" / "build_indian_testset.py"),
        "--list_categories"
    ],
    capture_output=True,
    text=True,
    cwd=str(WORK),
    env=env
)

print(result.stdout)
if result.stderr:
    print("STDERR:", result.stderr)

Assignment
Commercial Terms
Dispute Resolution
Governing Law / Jurisdiction
Intellectual Property
Liability
Non-Compete
Non-Solicitation
Other
Penalties
Termination
Warranty
Confidentiality
Force Majeure
Indemnification
Modification
Payment
Privacy / Data Protection

In [13]:
import subprocess
import sys
import os

env = os.environ.copy()
env["PYTHONPATH"] = (
    str(WORK) + os.pathsep +
    str(WORK / "indian_set") + os.pathsep +
    env.get("PYTHONPATH", "")
)

result = subprocess.run(
    [
        sys.executable,
        str(WORK / "indian_set" / "build_indian_testset.py"),
        "--docs_dir", str(WORK / "indian_set" / "documents"),
        "--clauses_csv", str(WORK / "indian_set" / "clauses.csv"),
        "--out_dir", str(WORK / "indian_set" / "built")
    ],
    capture_output=True,
    text=True,
    cwd=str(WORK),
    env=env
)

print("Return code:", result.returncode)
print(result.stdout)
if result.stderr:
    print("STDERR:", result.stderr)

Return code: 0
# Indian test set build report

2 clauses from 1 documents.

| Category | clauses | model has training data? |
|---|---|---|
| Confidentiality | 1 | no (never seen in training) |
| Indemnification | 1 | no (never seen in training) |

Categories with fewer than 3 clauses (too thin for per-category scores): Confidentiality, Indemnification

CSV encoding read as: utf-8

## Clauses per document

- aera_rfp_consultant_2025.txt: 2

Clauses in never-seen categories: 2 of 2
NOTE: Dispute Resolution is only 'seen' via CUAD's Covenant Not To Sue (no arbitration/forum clauses), so score it separately from the other seen categories.

## Warnings (rows kept, but check them)
- line 3: text ends in dot leaders or a page number -- probably a table-of-contents line

In [14]:
from pathlib import Path
import json

built = WORK / "indian_set" / "built"

report = built / "build_report.md"
mapped = built / "indian_mapped.jsonl"
contracts = built / "indian_contracts.json"

print("Generated files:")
for p in [report, mapped, contracts]:
    print(p.name, "exists:", p.exists())

print("\n--- Build report ---")
print(report.read_text(encoding="utf-8"))

print("\n--- Mapped clauses ---")
for line in mapped.read_text(encoding="utf-8").splitlines():
    row = json.loads(line)
    print(json.dumps(row, indent=2, ensure_ascii=False)[:2500])

Generated files:
build_report.md exists: True
indian_mapped.jsonl exists: True
indian_contracts.json exists: True

--- Build report ---
# Indian test set build report

2 clauses from 1 documents.

| Category | clauses | model has training data? |
|---|---|---|
| Confidentiality | 1 | no (never seen in training) |
| Indemnification | 1 | no (never seen in training) |

Categories with fewer than 3 clauses (too thin for per-category scores): Confidentiality, Indemnification

CSV encoding read as: utf-8

## Clauses per document

- aera_rfp_consultant_2025.txt: 2

Clauses in never-seen categories: 2 of 2
NOTE: Dispute Resolution is only 'seen' via CUAD's Covenant Not To Sue (no arbitration/forum clauses), so score it separately from the other seen categories.

## Warnings (rows kept, but check them)
- line 3: text ends in dot leaders or a page number -- probably a table-of-contents line

--- Mapped clauses ---
{
  "clause_id": "indian_aera_rfp_consultant_2025__Confidentiality__0",
  "contract_id": "indian_aera_rfp_consultant_2025",
  "cuad_category": "INDIAN_SET",
  "clausexplain_category": "Confidentiality",
  "clause_text": "Confidentiality The Consultant and its Key Personnel shall not, either during the term or within one year after the expiration or termination of this Agreement disclose any proprietary information, including information relating to reports, data, drawings, design software or other material, whether written or oral, in electronic or magnetic format, and the contents thereof; and any reports, digests or summaries created or derived from any of the foregoing that is provided by the Authority to the Consultant, its Key Personnel; any information provided by or relating to the Authority, its technology, technical processes, business affairs or finances or any information relating to the Authority’s employees, officers or other professionals or suppliers, customers, or contractors of the Authority; and any other information which the Consultant is under an obligation to keep confidential in relation to the Project, the Services or this Agreement (\"Confidential Information\"), without the prior written consent of the Authority.\n\nNotwithstanding the aforesaid, the Consultant, its Key Personnel or either of them may disclose, with prior written approval of the Authority, Confidential Information to the extent that such Confidential Information:\n\na) was in the public domain prior to its delivery to the Consultant, its Key Personnel or becomes a part of the public knowledge from a source other than the Consultant, its Key Personnel;\n\nb) was obtained from a third party with no known duty to maintain its confidentiality;\n\nc) is required to be disclosed by Applicable Laws or judicial or administrative or arbitral process or by any governmental instrumentalities, provided that for any such disclosure, the Consultant, its Key Personnel shall give the Authority, prompt written notice, and use reasonable efforts to ensure that such disclosure is accorded confidential treatment; and\n\nd) is provided to the professional advisers, agents, auditors or representatives of the Consultant or its Key Personnel, as is reasonable under the circumstances; provided, however, that the Consultant or Key Personnel, as the case may be, shall require their professional advisers, agents, auditors or its representatives, to undertake in writing to keep such Confident
{
  "clause_id": "indian_aera_rfp_consultant_2025__Indemnification__1",
  "contract_id": "indian_aera_rfp_consultant_2025",
  "cuad_category": "INDIAN_SET",
  "clausexplain_category": "Indemnification",
  "clause_text": "3.6.4\n\nThe Consultant shall hold the Authority harmless and indemnified for any losses, claims, damages, expenses (including all legal expenses), awards, penalties or injuries (collectively referred to as “Claims”) which may arise from or due to any unauthorized use of such Consultancy Documents, or due to any breach or failure on part of the Consultant (or any Third Party appointed by the Consultant) to perform any of its duties or obligations in relation to securing the aforementioned rights of the Authority.\n\n3.7\n\nMaterials furnished by the Authority Materials made available to the Consultant by the Authority shall be the property of the Authority and shall be marked accordingly. Upon termination or expiration of this Agreement, the Consultant shall furnish forthwith to the Authority, an inventory of such materials and shall dispose of such materials in accordance with the instructions of the Authority. The Consultant would be allowed to retain a copy of its working papers to maintain a professional record of its involvement in the engagement and to comply with applicable legal and regulatory requirements. Also, it is appreciated that it may not be possible for the Consultant to permanently dispose-off all information so furnished (for instance in terms of information embodied in project related emails). In all cases, the Consultant shall be responsible for not using such information for purposes unrelated to this Agreement without the prior written approval of the Authority.\n\n3.8\n\nAccuracy of Documents The Consultant shall be responsible for accuracy of the documents drafted and/ or vetted and data collected by it directly or procured from other agencies/ authorities, estimates and all other details prepared by it as part of these services. Subject to the provisions of Clause 3.4, it shall indemnify the Authority against any inaccuracy in its work which might surface during the currency of the assignment [i.e., till completion of milestone/ activity 4 as given in clause 2.4(d) of the RFP], if such inaccuracy is the result of any negligence or inadequate due diligence on part of the Consultant or arises out of its failure to conform to good industry practice. The Consultant shall also be responsible for promptly correcting, at

In [15]:
import csv
from pathlib import Path

indian = WORK / "indian_set"
csv_path = indian / "clauses.csv"

with csv_path.open(encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))

for i, row in enumerate(rows, start=1):
    clause = row["clause_text"].strip()
    print(f"\nRow {i}: {row['category']}")
    print("Document:", row["document_file"])
    print("Characters:", len(clause))
    print("Starts:", repr(clause[:180]))
    print("Ends:", repr(clause[-250:]))
    print("Contains next section heading 3.7:", "3.7" in clause)
    print("Contains dot leaders:", bool(__import__("re").search(r"\.{3,}", clause)))

Row 1: Confidentiality
Document: aera_rfp_consultant_2025.txt
Characters: 2523
Starts: 'Confidentiality The Consultant and its Key Personnel shall not, either during the term or within one year after the expiration or termination of this Agreement disclose any proprie'
Ends: 'formation, confidential and shall use its best efforts to ensure compliance with such undertaking.\n\nSubject to the confidentiality obligations above, the Consultant shall be allowed to use this engagement as an experience citation with other clients.'
Contains next section heading 3.7: False
Contains dot leaders: False

Row 2: Indemnification
Document: aera_rfp_consultant_2025.txt
Characters: 3046
Starts: '3.6.4\n\nThe Consultant shall hold the Authority harmless and indemnified for any losses, claims, damages, expenses (including all legal expenses), awards, penalties or injuries (col'
Ends: 'Key Personnel as may be required to carry out the Services.\n\n4.2\n\nDeployment of Key Personnel A list of Key Personnel deployed for this contract is placed at Annexure – I of this Agreement.\n\n4.3 5.\n\n5.1\n\nSubstitution of Key Personnel: As per clause 4'
Contains next section heading 3.7: True
Contains dot leaders: False

In [16]:
from pathlib import Path
import subprocess
import sys
import os

WORK = Path("/kaggle/working/indian_eval_project")
indian = WORK / "indian_set"

env = os.environ.copy()
env["PYTHONPATH"] = (
    str(WORK) + os.pathsep +
    str(indian) + os.pathsep +
    env.get("PYTHONPATH", "")
)

result = subprocess.run(
    [
        sys.executable,
        str(indian / "build_indian_testset.py"),
        "--docs_dir", str(indian / "documents"),
        "--clauses_csv", str(indian / "clauses.csv"),
        "--out_dir", str(indian / "built")
    ],
    capture_output=True,
    text=True,
    cwd=str(WORK),
    env=env
)

print("Return code:", result.returncode)
print(result.stdout)
if result.stderr:
    print("STDERR:", result.stderr)

Return code: 0
# Indian test set build report

2 clauses from 1 documents.

| Category | clauses | model has training data? |
|---|---|---|
| Confidentiality | 1 | no (never seen in training) |
| Indemnification | 1 | no (never seen in training) |

Categories with fewer than 3 clauses (too thin for per-category scores): Confidentiality, Indemnification

CSV encoding read as: utf-8

## Clauses per document

- aera_rfp_consultant_2025.txt: 2

Clauses in never-seen categories: 2 of 2
NOTE: Dispute Resolution is only 'seen' via CUAD's Covenant Not To Sue (no arbitration/forum clauses), so score it separately from the other seen categories.

## Warnings (rows kept, but check them)
- line 3: text ends in dot leaders or a page number -- probably a table-of-contents line

In [17]:
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")

print("Checkpoint files:")
for p in WORK.rglob("ckpt_joint_cls_span_fold0.pt"):
    print(p, "|", round(p.stat().st_size / (1024**2), 2), "MB")

print("\nConfiguration files:")
for p in WORK.rglob("config.json"):
    print(p)

print("\nEvaluation script:")
p = WORK / "indian_set" / "eval_indian.py"
print(p, "| exists:", p.exists())

Checkpoint files:
/kaggle/working/indian_eval_project/ckpt_joint_cls_span_fold0.pt | 567.29 MB

Configuration files:
/kaggle/working/indian_eval_project/partial/config.json

Evaluation script:
/kaggle/working/indian_eval_project/indian_set/eval_indian.py | exists: True

In [18]:
from pathlib import Path
import shutil

WORK = Path("/kaggle/working/indian_eval_project")
RULE_ROOT = Path("/kaggle/input")

# Find both required files in attached Kaggle datasets
engine_files = list(RULE_ROOT.rglob("rules_engine.py"))
rules_files = list(RULE_ROOT.rglob("indian_legal_rules.csv"))

print("Rule engine files:", engine_files)
print("Rules CSV files:", rules_files)

if not engine_files:
    raise FileNotFoundError("rules_engine.py not found in attached inputs.")

if not rules_files:
    raise FileNotFoundError("indian_legal_rules.csv not found in attached inputs.")

# Copy into the project root without modifying the source dataset
shutil.copy2(engine_files[0], WORK / "rules_engine.py")
shutil.copy2(rules_files[0], WORK / "indian_legal_rules.csv")

print("\nCopied successfully:")
print("Engine:", (WORK / "rules_engine.py").exists())
print("Rules:", (WORK / "indian_legal_rules.csv").exists())

Rule engine files: [PosixPath('/kaggle/input/datasets/riyasuryawanshi/rule-engine-v2/rules_engine.py')]
Rules CSV files: [PosixPath('/kaggle/input/datasets/riyasuryawanshi/scan-vs-span/indian_legal_rules.csv'), PosixPath('/kaggle/input/datasets/riyasuryawanshi/cuad-project/indian_legal_rules.csv'), PosixPath('/kaggle/input/datasets/riyasuryawanshi/cuad-project/phase3/indian_legal_rules.csv')]

Copied successfully:
Engine: True
Rules: True

In [19]:
from pathlib import Path
import subprocess
import sys
import os

WORK = Path("/kaggle/working/indian_eval_project")
indian = WORK / "indian_set"

env = os.environ.copy()
env["PYTHONPATH"] = (
    str(WORK) + os.pathsep +
    str(indian) + os.pathsep +
    env.get("PYTHONPATH", "")
)

cmd = [
    sys.executable,
    str(indian / "eval_indian.py"),
    "--run_dir", str(WORK),
    "--fold", "0",
    "--ckpt", str(WORK / "ckpt_joint_cls_span_fold0.pt"),
    "--indian_dir", str(indian / "built"),
    "--mapped_jsonl", str(WORK / "clauses_mapped.jsonl"),
    "--cuad_json", str(WORK / "CUAD_v1.json"),
    "--rules", str(WORK / "indian_legal_rules.csv"),
]

print("Starting evaluation...")
print("Command:", " ".join(cmd))

result = subprocess.run(
    cmd,
    capture_output=True,
    text=True,
    cwd=str(WORK),
    env=env
)

print("\nReturn code:", result.returncode)
print("\nSTDOUT:\n", result.stdout[-12000:])

if result.stderr:
    print("\nSTDERR:\n", result.stderr[-6000:])

Starting evaluation...
Command: /usr/bin/python3 /kaggle/working/indian_eval_project/indian_set/eval_indian.py --run_dir /kaggle/working/indian_eval_project --fold 0 --ckpt /kaggle/working/indian_eval_project/ckpt_joint_cls_span_fold0.pt --indian_dir /kaggle/working/indian_eval_project/indian_set/built --mapped_jsonl /kaggle/working/indian_eval_project/clauses_mapped.jsonl --cuad_json /kaggle/working/indian_eval_project/CUAD_v1.json --rules /kaggle/working/indian_eval_project/indian_legal_rules.csv

Return code: 0

STDOUT:
 2 Indian clauses: 0 in categories the model was trained on, 2 in categories it never saw
# Indian-context evaluation

2 clauses: 0 in categories seen in training, 2 in unseen categories. Small sample: read gaps, not decimals.

## Categories the model never saw: what it predicted instead

| True category | predictions |
|---|---|
| Confidentiality | Termination x1 |
| Indemnification | Intellectual Property x1 |

## Rule-layer findings (see indian_rule_flags.csv)

- ICA_S124_01:possible: 1



STDERR:
 Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/269 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 269/269 [00:00<00:00, 10424.82it/s]
[transformers] LongformerModel LOAD REPORT from: allenai/longformer-base-4096
Key                            | Status     |  |
-------------------------------+------------+--+-
lm_head.decoder.weight         | UNEXPECTED |  |
longformer.pooler.dense.weight | UNEXPECTED |  |
lm_head.layer_norm.weight      | UNEXPECTED |  |
lm_head.dense.bias             | UNEXPECTED |  |
longformer.pooler.dense.bias   | UNEXPECTED |  |
lm_head.dense.weight           | UNEXPECTED |  |
lm_head.bias                   | UNEXPECTED |  |
lm_head.layer_norm.bias        | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [20]:
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")

for p in sorted(WORK.rglob("*")):
    if p.is_file() and (
        "indian" in p.name.lower()
        or "rule" in p.name.lower()
        or "eval" in p.name.lower()
    ):
        print(p.relative_to(WORK), "-", round(p.stat().st_size / 1024, 1), "KB")

__pycache__/rules_engine.cpython-313.pyc - 38.9 KB
indian_legal_rules.csv - 10.9 KB
indian_set/__pycache__/build_indian_testset.cpython-313.pyc - 13.7 KB
indian_set/build_indian_testset.py - 8.6 KB
indian_set/built/indian_contracts.json - 117.6 KB
indian_set/built/indian_eval.json - 0.2 KB
indian_set/built/indian_eval.md - 0.4 KB
indian_set/built/indian_mapped.jsonl - 6.2 KB
indian_set/built/indian_rule_flags.csv - 0.6 KB
indian_set/eval_indian.py - 12.5 KB
rules_engine.py - 28.6 KB

In [21]:
from pathlib import Path
import pandas as pd

WORK = Path("/kaggle/working/indian_eval_project")
built = WORK / "indian_set" / "built"

print("=== INDIAN EVALUATION REPORT ===")
print((built / "indian_eval.md").read_text(encoding="utf-8"))

print("\n=== RULE FLAGS ===")
flags = pd.read_csv(built / "indian_rule_flags.csv")
display(flags)

print("\n=== EVALUATION JSON ===")
print((built / "indian_eval.json").read_text(encoding="utf-8"))

=== INDIAN EVALUATION REPORT ===
# Indian-context evaluation

2 clauses: 0 in categories seen in training, 2 in unseen categories. Small sample: read gaps, not decimals.

## Categories the model never saw: what it predicted instead

| True category | predictions |
|---|---|
| Confidentiality | Termination x1 |
| Indemnification | Intellectual Property x1 |

## Rule-layer findings (see indian_rule_flags.csv)

- ICA_S124_01:possible: 1


=== RULE FLAGS ===

,clause_id,category,rule_id,status,reasons,evidence,note,clause_text
0,indian_aera_rfp_consultant_2025__Indemnificati...,Indemnification,ICA_S124_01,possible,broad scope without a visible cap,all legal expenses,commercial-fairness concern only; Indian law d...,3.6.4\n\nThe Consultant shall hold the Authori...

=== EVALUATION JSON ===
{
 "n_total": 2,
 "n_seen": 0,
 "n_unseen": 2,
 "unseen_category_predictions": {
  "Confidentiality": {
   "Termination": 1
  },
  "Indemnification": {
   "Intellectual Property": 1
  }
 },
 "rule_status_counts": {
  "ICA_S124_01:possible": 1
 }
}

In [22]:
from pathlib import Path
import pandas as pd

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

print("Documents:", len(list((INDIAN / "documents").glob("*.txt"))))
print("Current annotations:")

df = pd.read_csv(INDIAN / "clauses.csv")
display(df)

print("\nAvailable helper files:")
for f in sorted(INDIAN.iterdir()):
    if f.is_file():
        print(f.name)

Documents: 11
Current annotations:

,document_file,category,clause_text,source_note
0,aera_rfp_consultant_2025.txt,Confidentiality,Confidentiality The Consultant and its Key Per...,AERA agreement; Confidentiality section
1,aera_rfp_consultant_2025.txt,Indemnification,3.6.4\n\nThe Consultant shall hold the Authori...,AERA agreement; clause 3.6.4

Available helper files:
aera_rfp_consultant_2025.txt
build_indian_testset.py
clause_browser.csv
clauses.csv
documents_manifest.csv
dot_unified_licence_agreement.txt
eval_indian.py
gem_general_terms_and_conditions.txt
himachal_hemodialysis_ppp_concession_agreement.txt
mea_architect_consultancy_agreement.txt
mea_pmc_services_agreement.txt
meity_msa_cloud_services_template.txt
mha_rfp_project_management_consultants.txt
noida_airport_concession_agreement.txt
prepare_documents.py
smoke_test.py
stqc_non_disclosure_agreement.txt
tender_consultancy_scc_1349.txt

In [23]:
for f in INDIAN.rglob("*clause*browser*.csv"):
    print("Found:", f)
    display(pd.read_csv(f).head(10))

Found: /kaggle/working/indian_eval_project/indian_set/clause_browser.csv

,document_file,"category_hint (keyword only, not a label)",paragraph_no,kind,heading,preview
0,aera_rfp_consultant_2025.txt,Termination,748,heading,"COMMENCEMENT, COMPLETION AND TERMINATION OF AG...","COMMENCEMENT, COMPLETION AND TERMINATION OF AG..."
1,aera_rfp_consultant_2025.txt,Termination,774,heading,Termination of Agreement,Termination of Agreement 2.10.1 By the Authori...
2,aera_rfp_consultant_2025.txt,Termination,791,heading,"Authority, in its sole discretion and for any ...","Authority, in its sole discretion and for any ..."
3,aera_rfp_consultant_2025.txt,Indemnification,821,heading,Indemnity As per GeM GTC.,Indemnity As per GeM GTC. 3.2 Conflict of Inte...
4,aera_rfp_consultant_2025.txt,Confidentiality,685,heading,“Confidential Information” shall have the mean...,“Confidential Information” shall have the mean...
5,aera_rfp_consultant_2025.txt,Confidentiality,852,heading,b) was obtained from a third party with no kno...,b) was obtained from a third party with no kno...
6,aera_rfp_consultant_2025.txt,Dispute Resolution,690,heading,“Dispute” shall have the meaning set forth in ...,“Dispute” shall have the meaning set forth in ...
7,aera_rfp_consultant_2025.txt,Dispute Resolution,796,heading,d) the Authority fails to comply with any fina...,d) the Authority fails to comply with any fina...
8,aera_rfp_consultant_2025.txt,Dispute Resolution,930,heading,Dispute resolution between the buyer and the s...,Dispute resolution between the buyer and the s...
9,aera_rfp_consultant_2025.txt,Governing Law / Jurisdiction,818,heading,Applicable Laws,Applicable Laws The Consultant shall perform t...

In [24]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

browser = pd.read_csv(INDIAN / "clause_browser.csv")
print("Total candidate entries:", len(browser))
print("\nEntry types:")
print(browser["kind"].value_counts(dropna=False))

# Keep entries that may contain actual clause text
candidates = browser[
    browser["kind"].astype(str).str.lower().ne("heading")
].copy()

# Remove very short or empty previews
candidates["preview"] = candidates["preview"].fillna("").astype(str)
candidates = candidates[
    candidates["preview"].str.len().between(100, 1500)
]

print("\nCandidate clauses:", len(candidates))
display(
    candidates[
        ["document_file", "category_hint (keyword only, not a label)",
         "paragraph_no", "kind", "preview"]
    ].head(30)
)

Total candidate entries: 471

Entry types:
kind
heading    370
body       101
Name: count, dtype: int64

Candidate clauses: 101

,document_file,"category_hint (keyword only, not a label)",paragraph_no,kind,preview
36,aera_rfp_consultant_2025.txt,Penalties,189,body,AERA reserves the right to extend the time per...
37,aera_rfp_consultant_2025.txt,Penalties,506,body,5. AERA will be entitled to deduct/ recover th...
38,aera_rfp_consultant_2025.txt,Penalties,509,body,"6. Notwithstanding the above, AERA reserves th..."
39,aera_rfp_consultant_2025.txt,Penalties,757,body,Extension of Contract Period: AERA reserves th...
40,aera_rfp_consultant_2025.txt,Non-Solicitation,517,body,"(a) “corrupt practice” means (i) the offering,..."
41,aera_rfp_consultant_2025.txt,Non-Solicitation,838,body,"“corrupt practice” means the offering, giving,..."
42,aera_rfp_consultant_2025.txt,Non-Compete,339,body,Bidder should not have a conflict of interest ...
43,aera_rfp_consultant_2025.txt,Non-Compete,521,body,(e) “restrictive practice” means forming a car...
44,aera_rfp_consultant_2025.txt,Non-Compete,848,body,“restrictive practice” means forming a cartel ...
45,aera_rfp_consultant_2025.txt,Indemnification,873,body,The Consultant shall hold the Authority harmle...
46,aera_rfp_consultant_2025.txt,Indemnification,877,body,Accuracy of Documents The Consultant shall be ...
47,aera_rfp_consultant_2025.txt,Force Majeure,506,body,5. AERA will be entitled to deduct/ recover th...
48,aera_rfp_consultant_2025.txt,Force Majeure,769,body,Force Majeure If at any time during the contin...
49,aera_rfp_consultant_2025.txt,Force Majeure,786,body,"as the result of Force Majeure, the Consultant..."
50,aera_rfp_consultant_2025.txt,Force Majeure,795,body,"c) as the result of the Force Majeure, the Con..."
51,aera_rfp_consultant_2025.txt,Confidentiality,849,body,Confidentiality The Consultant and its Key Per...
52,aera_rfp_consultant_2025.txt,Confidentiality,850,body,"Notwithstanding the aforesaid, the Consultant,..."
53,aera_rfp_consultant_2025.txt,Confidentiality,854,body,"d) is provided to the professional advisers, a..."
82,dot_unified_licence_agreement.txt,Penalties,63,body,: General Conditions Condition 1: Ownership of...
83,dot_unified_licence_agreement.txt,Penalties,435,body,The LICENSEE shall clearly define the scope of...
84,dot_unified_licence_agreement.txt,Penalties,666,body,5.9 The decision of the Ministry of Informatio...
85,dot_unified_licence_agreement.txt,Penalties,1726,body,4.8 For the purpose of calculation of delay in...
86,dot_unified_licence_agreement.txt,Non-Compete,218,body,"6.4 Further, the Licensee may transfer or assi..."
87,dot_unified_licence_agreement.txt,Indemnification,216,body,6.2 The Licensor shall have the right to direc...
88,dot_unified_licence_agreement.txt,Indemnification,446,body,"30.10 Any dispute, with regard to the provisio..."
89,dot_unified_licence_agreement.txt,Force Majeure,264,body,"12.2 However, the Force Majeure events noted a..."
90,dot_unified_licence_agreement.txt,Force Majeure,265,body,12.3 While it will normally not be a ground fo...
91,dot_unified_licence_agreement.txt,Confidentiality,498,body,38.3 In case any confidential information is d...
110,gem_general_terms_and_conditions.txt,Penalties,9,body,d. SERVICE LEVEL AGREEMENT (SLA)” shall mean t...
111,gem_general_terms_and_conditions.txt,Penalties,205,body,No increase in price on account of statutory i...

In [25]:
print("Candidate counts by document:")
display(
    candidates.groupby("document_file")
    .size()
    .sort_values(ascending=False)
    .rename("candidate_count")
    .reset_index()
)

print("\nCandidate counts by suggested category:")
display(
    candidates["category_hint (keyword only, not a label)"]
    .value_counts()
    .rename_axis("suggested_category")
    .reset_index(name="count")
)

Candidate counts by document:

                                       document_file  candidate_count
0                       aera_rfp_consultant_2025.txt               18
1              meity_msa_cloud_services_template.txt               18
2             noida_airport_concession_agreement.txt               15
3  himachal_hemodialysis_ppp_concession_agreement...               13
4                  dot_unified_licence_agreement.txt               10
5               gem_general_terms_and_conditions.txt                9
6         mha_rfp_project_management_consultants.txt                7
7                  stqc_non_disclosure_agreement.txt                6
8                     mea_pmc_services_agreement.txt                3
9            mea_architect_consultancy_agreement.txt                2

Candidate counts by suggested category:

  suggested_category  count
0          Penalties     27
1      Force Majeure     26
2    Indemnification     17
3    Confidentiality     16
4        Non-Compete     11
5   Non-Solicitation      4

In [26]:
from pathlib import Path
import pandas as pd
import re

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

browser = pd.read_csv(INDIAN / "clause_browser.csv")
docs_dir = INDIAN / "documents"

rows = []

for _, row in browser.iterrows():
    if str(row.get("kind", "")).lower() != "body":
        continue

    filename = row["document_file"]
    doc_path = docs_dir / filename

    if not doc_path.exists():
        continue

    text = doc_path.read_text(encoding="utf-8", errors="replace")
    paragraphs = re.split(r"\n\s*\n", text)

    paragraph_no = int(row["paragraph_no"])
    if paragraph_no < 0 or paragraph_no >= len(paragraphs):
        continue

    clause_text = paragraphs[paragraph_no].strip()

    if len(clause_text) < 100:
        continue

    rows.append({
        "document_file": filename,
        "paragraph_no": paragraph_no,
        "category_hint": row.get(
            "category_hint (keyword only, not a label)", ""
        ),
        "clause_text": clause_text,
        "verified_category": "",
        "review_notes": ""
    })

review = pd.DataFrame(rows).drop_duplicates(
    subset=["document_file", "paragraph_no"]
)

out_path = INDIAN / "clause_review.csv"
review.to_csv(out_path, index=False)

print("Review rows:", len(review))
print("Saved to:", out_path)
display(review[
    ["document_file", "paragraph_no", "category_hint", "clause_text"]
].head(5))

Review rows: 98
Saved to: /kaggle/working/indian_eval_project/indian_set/clause_review.csv

,document_file,paragraph_no,category_hint,clause_text
0,aera_rfp_consultant_2025.txt,189,Penalties,AERA reserves the right to extend the time per...
1,aera_rfp_consultant_2025.txt,506,Penalties,5. AERA will be entitled to deduct/ recover th...
2,aera_rfp_consultant_2025.txt,509,Penalties,"6. Notwithstanding the above, AERA reserves th..."
3,aera_rfp_consultant_2025.txt,757,Penalties,Extension of Contract Period: AERA reserves th...
4,aera_rfp_consultant_2025.txt,517,Non-Solicitation,"(a) “corrupt practice” means (i) the offering,..."

In [27]:
from pathlib import Path
import pandas as pd
import re

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review = pd.read_csv(INDIAN / "clause_review.csv")

# Check the first 5 extracted clauses against the source paragraphs
for _, row in review.head(5).iterrows():
    source = (INDIAN / "documents" / row["document_file"]).read_text(
        encoding="utf-8", errors="replace"
    )
    paragraphs = re.split(r"\n\s*\n", source)
    n = int(row["paragraph_no"])

    extracted = row["clause_text"].strip()
    source_paragraph = paragraphs[n].strip() if n < len(paragraphs) else ""

    print("=" * 80)
    print("Document:", row["document_file"])
    print("Paragraph:", n)
    print("Exact match:", extracted == source_paragraph)
    print("Extracted:", extracted[:250])
    print("Source:   ", source_paragraph[:250])

================================================================================
Document: aera_rfp_consultant_2025.txt
Paragraph: 189
Exact match: True
Extracted: AERA reserves the right to extend the time period for completion of tariff determination exercise beyond six months, at its sole discretion, without any financial implication to AERA and without imposition of liquidated damages to the selected consul
Source:    AERA reserves the right to extend the time period for completion of tariff determination exercise beyond six months, at its sole discretion, without any financial implication to AERA and without imposition of liquidated damages to the selected consul
================================================================================
Document: aera_rfp_consultant_2025.txt
Paragraph: 506
Exact match: True
Extracted: 5. AERA will be entitled to deduct/ recover the Liquidated Damages for the delay, unless covered under Force Majeure conditions and/ or for any reasons not attributable to the consultant, @ 0.5% of the contract value of delayed quantity per week or p
Source:    5. AERA will be entitled to deduct/ recover the Liquidated Damages for the delay, unless covered under Force Majeure conditions and/ or for any reasons not attributable to the consultant, @ 0.5% of the contract value of delayed quantity per week or p
================================================================================
Document: aera_rfp_consultant_2025.txt
Paragraph: 509
Exact match: True
Extracted: 6. Notwithstanding the above, AERA reserves the right to extend the contract period for completion of assignment beyond the original period, without any financial implication to AERA and without imposition of liquidated damages to consultant.
Source:    6. Notwithstanding the above, AERA reserves the right to extend the contract period for completion of assignment beyond the original period, without any financial implication to AERA and without imposition of liquidated damages to consultant.
================================================================================
Document: aera_rfp_consultant_2025.txt
Paragraph: 757
Exact match: True
Extracted: Extension of Contract Period: AERA reserves the right to extend the contract period for completion of assignment beyond the original period, at its own discretion, for excusable delay not attributable to Consultant without any liquidated damages and
Source:    Extension of Contract Period: AERA reserves the right to extend the contract period for completion of assignment beyond the original period, at its own discretion, for excusable delay not attributable to Consultant without any liquidated damages and
================================================================================
Document: aera_rfp_consultant_2025.txt
Paragraph: 517
Exact match: True
Extracted: (a) “corrupt practice” means (i) the offering, giving, receiving, or soliciting, directly or indirectly, of anything of value to influence the action of any person connected with the Selection Process (for avoidance of doubt, offering of employment t
Source:    (a) “corrupt practice” means (i) the offering, giving, receiving, or soliciting, directly or indirectly, of anything of value to influence the action of any person connected with the Selection Process (for avoidance of doubt, offering of employment t

In [28]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review = pd.read_csv(INDIAN / "clause_review.csv")

# Prefer a spread across source agreements
review = review.sample(frac=1, random_state=42)
shortlist = (
    review.groupby("document_file", group_keys=False)
    .head(5)
    .head(45)
    .copy()
)

# These are blank intentionally: hints are not ground-truth labels
shortlist["verified_category"] = ""
shortlist["review_notes"] = ""

out = INDIAN / "clause_shortlist.csv"
shortlist.to_csv(out, index=False)

print("Shortlisted clauses:", len(shortlist))
print("Agreements represented:", shortlist["document_file"].nunique())
print("Saved to:", out)

display(shortlist[
    ["document_file", "paragraph_no", "category_hint", "clause_text"]
].head(10))

Shortlisted clauses: 45
Agreements represented: 10
Saved to: /kaggle/working/indian_eval_project/indian_set/clause_shortlist.csv

,document_file,paragraph_no,category_hint,clause_text
62,meity_msa_cloud_services_template.txt,519,Force Majeure,a. “Force Majeure” shall mean any event beyond...
40,himachal_hemodialysis_ppp_concession_agreement...,499,Indemnification,"Shall be liable for and shall indemnify, prote..."
94,stqc_non_disclosure_agreement.txt,19,Confidentiality,(a) The term “Confidential Information” shall ...
18,dot_unified_licence_agreement.txt,435,Penalties,The LICENSEE shall clearly define the scope of...
81,noida_airport_concession_agreement.txt,832,Non-Compete,(6) not less than (4 (four) kiosks or outlets ...
83,noida_airport_concession_agreement.txt,1963,Non-Compete,Parking of vehicles 1k wll be our endeavour to...
64,meity_msa_cloud_services_template.txt,532,Force Majeure,No delay or nonperformance by either party to ...
42,himachal_hemodialysis_ppp_concession_agreement...,1000,Indemnification,The Concessionaire shall provide fair and just...
10,aera_rfp_consultant_2025.txt,877,Indemnification,Accuracy of Documents The Consultant shall be ...
0,aera_rfp_consultant_2025.txt,189,Penalties,AERA reserves the right to extend the time per...

In [29]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review = pd.read_csv(INDIAN / "clause_review.csv")
review["clause_text"] = review["clause_text"].fillna("").astype(str)
review["category_hint"] = review["category_hint"].fillna("").astype(str)

# Rank candidates by likely relevance to contractual provisions.
# This is a screening aid, NOT an automatic ground-truth label.
terms = [
    "shall", "liable", "indemnify", "confidential", "terminate",
    "termination", "dispute", "arbitration", "governing law",
    "intellectual property", "payment", "penalty", "damages",
    "force majeure", "personal data", "privacy", "warranty",
    "assign", "assignment", "limitation of liability"
]

review["relevance_score"] = review["clause_text"].str.lower().apply(
    lambda text: sum(term in text for term in terms)
)

ranked = review.sort_values(
    ["relevance_score"], ascending=False
).drop_duplicates(
    subset=["document_file", "paragraph_no"]
).head(45).copy()

ranked["verified_category"] = ""
ranked["review_notes"] = ""

out = INDIAN / "clause_shortlist_v2.csv"
ranked.to_csv(out, index=False)

print("Candidates for review:", len(ranked))
print("Agreements represented:", ranked["document_file"].nunique())
print("Saved to:", out)

display(ranked[
    ["document_file", "paragraph_no", "category_hint",
     "relevance_score", "clause_text"]
].head(15))

Candidates for review: 45
Agreements represented: 10
Saved to: /kaggle/working/indian_eval_project/indian_set/clause_shortlist_v2.csv

,document_file,paragraph_no,category_hint,relevance_score,clause_text
11,aera_rfp_consultant_2025.txt,769,Force Majeure,5,Force Majeure If at any time during the contin...
80,noida_airport_concession_agreement.txt,1107,Penalties,5,32:7.Penalty for evasion of Fees Inthe event t...
50,mea_pmc_services_agreement.txt,145,Force Majeure,4,10.1 In the event that either party is prevent...
77,noida_airport_concession_agreement.txt,450,Penalties,4,"references to any date, period or Project Mile..."
47,mea_architect_consultancy_agreement.txt,129,Force Majeure,4,In the event that either party is prevented wh...
85,noida_airport_concession_agreement.txt,1382,Indemnification,4,Without limiting the generality ofthe provisio...
10,aera_rfp_consultant_2025.txt,877,Indemnification,4,Accuracy of Documents The Consultant shall be ...
23,dot_unified_licence_agreement.txt,446,Indemnification,3,"30.10 Any dispute, with regard to the provisio..."
2,aera_rfp_consultant_2025.txt,509,Penalties,3,"6. Notwithstanding the above, AERA reserves th..."
1,aera_rfp_consultant_2025.txt,506,Penalties,3,5. AERA will be entitled to deduct/ recover th...
34,gem_general_terms_and_conditions.txt,246,Force Majeure,3,Liquidated Damages: If the Seller fails to del...
46,himachal_hemodialysis_ppp_concession_agreement...,870,Force Majeure,3,Save and except as expressly provided in this ...
48,mea_architect_consultancy_agreement.txt,151,Force Majeure,3,i. This AGREEMENT shall without prejudice to t...
3,aera_rfp_consultant_2025.txt,757,Penalties,3,Extension of Contract Period: AERA reserves th...
14,aera_rfp_consultant_2025.txt,849,Confidentiality,3,Confidentiality The Consultant and its Key Per...

In [30]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

ranked = pd.read_csv(INDIAN / "clause_shortlist_v2.csv")

# Preserve existing annotations
existing = pd.read_csv(INDIAN / "clauses.csv")

# Remove candidates already represented by the same source paragraph
# (we retain the existing annotations separately)
review = ranked.copy()
review["verified_category"] = ""
review["include_in_testset"] = ""
review["review_notes"] = ""

# Keep the clause text readable in the review sheet
review["clause_length"] = review["clause_text"].fillna("").str.len()

out = INDIAN / "category_review.csv"
review.to_csv(out, index=False)

print("Review sheet:", out)
print("Candidates:", len(review))
print("Existing annotations preserved:", len(existing))
display(review[
    ["document_file", "paragraph_no", "category_hint",
     "clause_length", "clause_text"]
].head(15))

Review sheet: /kaggle/working/indian_eval_project/indian_set/category_review.csv
Candidates: 45
Existing annotations preserved: 2

,document_file,paragraph_no,category_hint,clause_length,clause_text
0,aera_rfp_consultant_2025.txt,769,Force Majeure,1741,Force Majeure If at any time during the contin...
1,noida_airport_concession_agreement.txt,1107,Penalties,546,32:7.Penalty for evasion of Fees Inthe event t...
2,mea_pmc_services_agreement.txt,145,Force Majeure,794,10.1 In the event that either party is prevent...
3,noida_airport_concession_agreement.txt,450,Penalties,3558,"references to any date, period or Project Mile..."
4,mea_architect_consultancy_agreement.txt,129,Force Majeure,789,In the event that either party is prevented wh...
5,noida_airport_concession_agreement.txt,1382,Indemnification,1069,Without limiting the generality ofthe provisio...
6,aera_rfp_consultant_2025.txt,877,Indemnification,862,Accuracy of Documents The Consultant shall be ...
7,dot_unified_licence_agreement.txt,446,Indemnification,383,"30.10 Any dispute, with regard to the provisio..."
8,aera_rfp_consultant_2025.txt,509,Penalties,242,"6. Notwithstanding the above, AERA reserves th..."
9,aera_rfp_consultant_2025.txt,506,Penalties,459,5. AERA will be entitled to deduct/ recover th...
10,gem_general_terms_and_conditions.txt,246,Force Majeure,473,Liquidated Damages: If the Seller fails to del...
11,himachal_hemodialysis_ppp_concession_agreement...,870,Force Majeure,340,Save and except as expressly provided in this ...
12,mea_architect_consultancy_agreement.txt,151,Force Majeure,653,i. This AGREEMENT shall without prejudice to t...
13,aera_rfp_consultant_2025.txt,757,Penalties,280,Extension of Contract Period: AERA reserves th...
14,aera_rfp_consultant_2025.txt,849,Confidentiality,1035,Confidentiality The Consultant and its Key Per...

In [31]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review = pd.read_csv(INDIAN / "category_review.csv")

# Display the first 10 candidates with their full text
for i, row in review.head(10).iterrows():
    print("\n" + "=" * 90)
    print(f"Candidate {i + 1}")
    print("Document:", row["document_file"])
    print("Paragraph:", row["paragraph_no"])
    print("Keyword hint:", row["category_hint"])
    print("Length:", len(str(row["clause_text"])))
    print("\nFULL CLAUSE TEXT:\n")
    print(row["clause_text"])

==========================================================================================
Candidate 1
Document: aera_rfp_consultant_2025.txt
Paragraph: 769
Keyword hint: Force Majeure
Length: 1741

FULL CLAUSE TEXT:

Force Majeure If at any time during the continuance of the Contract, the performance in whole or in part by either party of any obligation under this Contract shall be prevented or delayed by the reasons of any war, hostility, acts of the public enemy, epidemics, civil commotion, sabotage, fires, floods, explosion, quarantine restrictions, strikes, lockouts or act of God (but not including negligence or wrongdoing, predictable/ seasonal rain) provided notice of happening of such event duly evidenced with documents is given by one party to the other within10 days from the date of occurrence thereof, neither party shall be by reasons of such event, be entitled to terminate the Contract nor shall either party have any claim for damages against the other in respect of such non-performance or the delay in performance, and deliveries under the contract shall be resumed as soon as practicable after such event has come to an end or ceased to exist, and the decision of the Buyer as to whether the deliveries have been so resumed or not, shall be final and conclusive, Provided further that if the performance in whole or part of any obligation under this contract is prevented or delayed by reason of any such event for a period exceeding 90 days, either party may at its option terminate the contract provided also that the Buyer shall be at liberty to take over from the Seller at a price to be fixed by Buyer, which shall be final, all unused, undamaged and accepted material, bought out components and Goods in course of manufacture in the possession of the Seller at the time of such termination or such portion thereof as the Buyer may deem fit excepting such materials, bought out components and Goods as the Seller may with the

==========================================================================================
Candidate 2
Document: noida_airport_concession_agreement.txt
Paragraph: 1107
Keyword hint: Penalties
Length: 546

FULL CLAUSE TEXT:

32:7.Penalty for evasion of Fees Inthe event that any User uses the Aixport without payment ofthe Fee due the Concessionaite shall subject to Applicable Laws and Applicable Permits, be eniled to determine and collect from such person, the Fee due and upto twice the amount thereof towards Damages for attempt to make unauthorised use of the Airpost, provided thatthe determination and collection of such Fee and Damages shall be a the risk and cost ofthe Concessionare and the Authority shall not be able on this account in any manner whatsoever.

==========================================================================================
Candidate 3
Document: mea_pmc_services_agreement.txt
Paragraph: 145
Keyword hint: Force Majeure
Length: 794

FULL CLAUSE TEXT:

10.1 In the event that either party is prevented wholly or in part, by any force majeure cause, as defined hereinafter from performing or accepting performance by the other party, the parties will either agree to a fresh completion date by condoning the period of delay arising out of such non-performance or may by mutual consent, treat the contract as terminated. However, if the force majeure conditions persist for an unreasonably long time, the party not under force majeure conditions may, by giving a notice to the other party, terminate the contract. In either case of termination, both parties will have no claim for compensation against each other, but shall receive their dues as prevailing on the date of commencement of force majeure conditions. Force Majeure is herein defined as:

==========================================================================================
Candidate 4
Document: noida_airport_concession_agreement.txt
Paragraph: 450
Keyword hint: Penalties
Length: 3558

FULL CLAUSE TEXT:

references to any date, period or Project Milestone shall mean and include such date, periodor Project Milestone as may be extended pursuant to this Agreement: any reference to any period commencing “from” a specified day or date and “tl” or “unlit” a specified day or date shall include both such daysor dates: provided that if the last day of any period computed under this Agreement is aot a business day. then the period shall run until the end of the next business day ‘the words importing singular shall include plural and vice versa: references to any gender shall include the other and the neural gender lakh” means a hundred thousand (100,000) and “erore” means ten_ milion (10,000,000) indebtedness” shall be construed so as to include any obligation (whether incurred 3s, Principal or surety) for the payment or repayment of money, whether present or future, ‘ctl or contingent; oF “reorganisation vency” ” of,2 references tothe “windi up", “dissolution”, “insol analogous or equivalent any ‘company or corporation shall be construed so as to include proceedings under the law ofthe jurisdiction in which such company or corporation is incorporated or any jurisdiction in which such company or corporation carries on business including the secking of liquidation, winding-up, reorganisation, dissolution, or relief of debtors: arrangement, protection save and except as otherwise provided inthis Agreement, any reference, at anytime, to any agreement, deed, instrument, licence or document of any description shall be or other document as ‘construed as reference to that agreement, deed instrument, licence amended, varied, supplemented, modified or suspended at the timeof such reference: provided that this Sub-clause (t) shal not operate so as to increase lisiltes or or pursuant ‘obligations of the Authority hereund er hereto in any manner whatsoever any agreement, consent, approval, authorisation, notice, communication, information or report required under or pursuant to this Agreement from or by any Party of the Independent Engineer shall be valid and effective only if it is im writing unde the hand such Party or the Independent Engineer, asthe ease of ive ‘of a duly authorised representat ray be. inthis behalf and not otherwise: to this Agreement form an integral part of this Agreement and the Schedles and Recitals will bein full force and effect as though they were expressly set out inthe body ofthis Agreement: references to Recitals, Amicles, Clauses, Sub-clauses, Provisos or Schedules in this Agreement shall, except where the context otherwise requires, mean references 10 this Agreement of or toes Recitals, Antcles, Clauses, Sub<lauses, Provisos and Schedul reference to an Annex shall, subject to anything to the contrary specified therein, be ‘construed as reference to an Annex to the Schedule in which such reference occurs; and reference toa Paragraph shal, subject t anything t the contrary specified therein, be ‘construed asa reference toa Paragraph ofthe Schedule or Annex, a the ease maybe, i which such reference appears the damages payable by either Party tothe other of them, asset forth in tis Agreement, ‘whether on per diem basisor otherwise, are mutually agreed genuine pre-stimated loss and damage likely to he suffered and incurred by the Party entitled to receive the same and are not by way of penalty (the “Damages"); and time shall be ofthe essence in the pesformance ofthe Parties’ respective obligations. If any time period specified herein is extended, such extended time shall also be ofthe Fa

==========================================================================================
Candidate 5
Document: mea_architect_consultancy_agreement.txt
Paragraph: 129
Keyword hint: Force Majeure
Length: 789

FULL CLAUSE TEXT:

In the event that either party is prevented wholly or in part, by any force majeure cause, as defined hereinafter from performing or accepting performance by the other party, the parties will either agree to a fresh completion date by condoning the period of delay arising out of such non-performance or may by mutual consent, treat the contract as terminated. However, if the force majeure conditions persist for an unreasonably long time, the party not under force majeure conditions may, by giving a notice to the other party, terminate the contract. In either case of termination, both parties will have no claim for compensation against each other, but shall receive their dues as prevailing on the date of commencement of force majeure conditions. Force Majeure is herein defined as:

==========================================================================================
Candidate 6
Document: noida_airport_concession_agreement.txt
Paragraph: 1382
Keyword hint: Indemnification
Length: 1069

FULL CLAUSE TEXT:

Without limiting the generality ofthe provisions of this Article 47, the Concessionaire shall fully indemnify, hold harmless and defend the Government Indemnified Persons from and against any and all suis, proceedings, actions, claims, demands, liabilities and damages Which the Government Indemnified Persons may herealter suffer, or pay by reason of any ‘demands, claims, suits or proceedings arising oat of claims of infingement of any domestic for foreign patent sighs, copyrights or other intellectual property. proprietary or <confidemality rights with respect to any materials, information, design or process used by the Concessionaize or by the Concessionare's Contractors in performing the ‘Concessionare's obligations orn any way incorporated in or related to the Project. fn any such suit action, claim or proceedings, a temporary restraint order or preliminary injunetion| is granted, the Concessionireshall make every reasonable effort, by giving a satisfactory hond or otherwise, to secure the revocation or suspension ofthe injunction or restraint onder.

==========================================================================================
Candidate 7
Document: aera_rfp_consultant_2025.txt
Paragraph: 877
Keyword hint: Indemnification
Length: 862

FULL CLAUSE TEXT:

Accuracy of Documents The Consultant shall be responsible for accuracy of the documents drafted and/ or vetted and data collected by it directly or procured from other agencies/ authorities, estimates and all other details prepared by it as part of these services. Subject to the provisions of Clause 3.4, it shall indemnify the Authority against any inaccuracy in its work which might surface during the currency of the assignment [i.e., till completion of milestone/ activity 4 as given in clause 2.4(d) of the RFP], if such inaccuracy is the result of any negligence or inadequate due diligence on part of the Consultant or arises out of its failure to conform to good industry practice. The Consultant shall also be responsible for promptly correcting, at its own cost and risk, the documents including any re-survey / investigations, during the said period.

==========================================================================================
Candidate 8
Document: dot_unified_licence_agreement.txt
Paragraph: 446
Keyword hint: Indemnification
Length: 383

FULL CLAUSE TEXT:

30.10 Any dispute, with regard to the provision of Service shall be a matter only between the aggrieved party and the Licensee, who shall duly notify this to all before providing the Service. And in no case, the Licensor shall bear any liability or responsibility in the matter. The LICENSEE shall keep the Licensor indemnified for all claims, cost, charges or damages in the matter.

==========================================================================================
Candidate 9
Document: aera_rfp_consultant_2025.txt
Paragraph: 509
Keyword hint: Penalties
Length: 242

FULL CLAUSE TEXT:

6. Notwithstanding the above, AERA reserves the right to extend the contract period for completion of assignment beyond the original period, without any financial implication to AERA and without imposition of liquidated damages to consultant.

==========================================================================================
Candidate 10
Document: aera_rfp_consultant_2025.txt
Paragraph: 506
Keyword hint: Penalties
Length: 459

FULL CLAUSE TEXT:

5. AERA will be entitled to deduct/ recover the Liquidated Damages for the delay, unless covered under Force Majeure conditions and/ or for any reasons not attributable to the consultant, @ 0.5% of the contract value of delayed quantity per week or part thereof of delayed period, until actual delivery or performance, as preestimated damages not exceeding 10% of the contract value of delayed quantity without any controversy/ dispute of any sort whatsoever.

In [32]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review_path = INDIAN / "category_review.csv"
review = pd.read_csv(review_path)

labels = {
    0: ("Force Majeure", "yes", "Force majeure and contract performance"),
    1: ("Penalties", "yes", "Damages for fee evasion"),
    2: ("Force Majeure", "yes", "Force majeure and termination"),
    3: ("Commercial Terms", "no", "Overly broad definitions and interpretation"),
    4: ("Force Majeure", "no", "Duplicate of Candidate 3"),
    5: ("Indemnification", "yes", "Intellectual property infringement indemnity"),
    6: ("Indemnification", "yes", "Indemnity for inaccurate work"),
    7: ("Indemnification", "yes", "Licensor indemnity"),
    8: ("Commercial Terms", "no", "Contract-period extension"),
    9: ("Penalties", "yes", "Liquidated damages for delay"),
}

for idx, (category, include, note) in labels.items():
    review.loc[idx, "verified_category"] = category
    review.loc[idx, "include_in_testset"] = include
    review.loc[idx, "review_notes"] = note

review.to_csv(review_path, index=False)

print("Saved verified labels:", review_path)
display(review.loc[:9, [
    "document_file",
    "category_hint",
    "verified_category",
    "include_in_testset",
    "review_notes"
]])

Saved verified labels: /kaggle/working/indian_eval_project/indian_set/category_review.csv

/tmp/ipykernel_49/3255996447.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Force Majeure' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  review.loc[idx, "verified_category"] = category
/tmp/ipykernel_49/3255996447.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'yes' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  review.loc[idx, "include_in_testset"] = include
/tmp/ipykernel_49/3255996447.py:26: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Force majeure and contract performance' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  review.loc[idx, "review_notes"] = note

,document_file,category_hint,verified_category,include_in_testset,review_notes
0,aera_rfp_consultant_2025.txt,Force Majeure,Force Majeure,yes,Force majeure and contract performance
1,noida_airport_concession_agreement.txt,Penalties,Penalties,yes,Damages for fee evasion
2,mea_pmc_services_agreement.txt,Force Majeure,Force Majeure,yes,Force majeure and termination
3,noida_airport_concession_agreement.txt,Penalties,Commercial Terms,no,Overly broad definitions and interpretation
4,mea_architect_consultancy_agreement.txt,Force Majeure,Force Majeure,no,Duplicate of Candidate 3
5,noida_airport_concession_agreement.txt,Indemnification,Indemnification,yes,Intellectual property infringement indemnity
6,aera_rfp_consultant_2025.txt,Indemnification,Indemnification,yes,Indemnity for inaccurate work
7,dot_unified_licence_agreement.txt,Indemnification,Indemnification,yes,Licensor indemnity
8,aera_rfp_consultant_2025.txt,Penalties,Commercial Terms,no,Contract-period extension
9,aera_rfp_consultant_2025.txt,Penalties,Penalties,yes,Liquidated damages for delay

In [33]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"
review_path = INDIAN / "category_review.csv"

review = pd.read_csv(review_path)

# Ensure review fields are text columns
for col in ["verified_category", "include_in_testset", "review_notes"]:
    review[col] = review[col].fillna("").astype(str)

review.to_csv(review_path, index=False)

print("Review file saved:", review_path)
print("\nVerified labels so far:")
print(review["verified_category"].ne("").sum())
print("Marked for inclusion:", (review["include_in_testset"] == "yes").sum())
print("Marked for exclusion:", (review["include_in_testset"] == "no").sum())

display(review.loc[:9, [
    "verified_category", "include_in_testset", "review_notes"
]])

Review file saved: /kaggle/working/indian_eval_project/indian_set/category_review.csv

Verified labels so far:
10
Marked for inclusion: 7
Marked for exclusion: 3

,verified_category,include_in_testset,review_notes
0,Force Majeure,yes,Force majeure and contract performance
1,Penalties,yes,Damages for fee evasion
2,Force Majeure,yes,Force majeure and termination
3,Commercial Terms,no,Overly broad definitions and interpretation
4,Force Majeure,no,Duplicate of Candidate 3
5,Indemnification,yes,Intellectual property infringement indemnity
6,Indemnification,yes,Indemnity for inaccurate work
7,Indemnification,yes,Licensor indemnity
8,Commercial Terms,no,Contract-period extension
9,Penalties,yes,Liquidated damages for delay

**11-20**

In [34]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review = pd.read_csv(INDIAN / "category_review.csv")

for i in range(10, min(20, len(review))):
    row = review.iloc[i]

    print("\n" + "=" * 90)
    print(f"Candidate {i + 1}")
    print("Document:", row["document_file"])
    print("Paragraph:", row["paragraph_no"])
    print("Keyword hint:", row["category_hint"])
    print("Already labelled:", row["verified_category"] or "No")
    print("Length:", len(str(row["clause_text"])))
    print("\nFULL CLAUSE TEXT:\n")
    print(row["clause_text"])

==========================================================================================
Candidate 11
Document: gem_general_terms_and_conditions.txt
Paragraph: 246
Keyword hint: Force Majeure
Already labelled: nan
Length: 473

FULL CLAUSE TEXT:

Liquidated Damages: If the Seller fails to deliver any or all of the Goods/Services within the original/re-fixed delivery period(s) specified in the contract, the Buyer will be entitled to deduct/recover the Liquidated Damages for the delay, unless covered under Force Majeure conditions aforesaid, @ 0.5% per week or part of the week of delayed period as pre-estimated damages not exceeding 10% of the contract value without any controversy/dispute of any sort whatsoever.

==========================================================================================
Candidate 12
Document: himachal_hemodialysis_ppp_concession_agreement.txt
Paragraph: 870
Keyword hint: Force Majeure
Already labelled: nan
Length: 340

FULL CLAUSE TEXT:

Save and except as expressly provided in this Article neither party hereto shall be liable in any manner whatsoever to other Party in respect of any loss, damage, cost, expense, claims, demand and proceedings relating to or arising out of occurrence or existence of any Force Majeure Event or exercise of any right pursuant to this Article.

==========================================================================================
Candidate 13
Document: mea_architect_consultancy_agreement.txt
Paragraph: 151
Keyword hint: Force Majeure
Already labelled: nan
Length: 653

FULL CLAUSE TEXT:

i. This AGREEMENT shall without prejudice to the provision of Section 11 (Force Majeure) and Section 15 (Termination) remains in force till the successful commissioning of the project which is expected as per the contractor’s work i.e. ___ (To be indicated by the Mission/Post) months or till completion of the work whichever is later. ii. If, however, due to some unavoidable reasons the successful commissioning of the project gets delayed, the validity of the agreement, as provided in Section 14 may be suitably extended by way of an amended agreement duly executed by the parties’ upto ___ months, or till completion of the work whichever is later.

==========================================================================================
Candidate 14
Document: aera_rfp_consultant_2025.txt
Paragraph: 757
Keyword hint: Penalties
Already labelled: nan
Length: 280

FULL CLAUSE TEXT:

Extension of Contract Period: AERA reserves the right to extend the contract period for completion of assignment beyond the original period, at its own discretion, for excusable delay not attributable to Consultant without any liquidated damages and financial implication to AERA.

==========================================================================================
Candidate 15
Document: aera_rfp_consultant_2025.txt
Paragraph: 849
Keyword hint: Confidentiality
Already labelled: nan
Length: 1035

FULL CLAUSE TEXT:

Confidentiality The Consultant and its Key Personnel shall not, either during the term or within one year after the expiration or termination of this Agreement disclose any proprietary information, including information relating to reports, data, drawings, design software or other material, whether written or oral, in electronic or magnetic format, and the contents thereof; and any reports, digests or summaries created or derived from any of the foregoing that is provided by the Authority to the Consultant, its Key Personnel; any information provided by or relating to the Authority, its technology, technical processes, business affairs or finances or any information relating to the Authority’s employees, officers or other professionals or suppliers, customers, or contractors of the Authority; and any other information which the Consultant is under an obligation to keep confidential in relation to the Project, the Services or this Agreement ("Confidential Information"), without the prior written consent of the Authority.

==========================================================================================
Candidate 16
Document: dot_unified_licence_agreement.txt
Paragraph: 63
Keyword hint: Penalties
Already labelled: nan
Length: 673

FULL CLAUSE TEXT:

: General Conditions Condition 1: Ownership of the Licensee Company Condition 2: Scope of the License Condition 3: Duration of License Condition 4: Renewal of License Condition 5: Modifications in the Terms and Conditions of License Condition 6: Restrictions on ‘Transfer of License’ Condition 7: Provision of Service Condition 8: Delivery of Service Condition 9: Requirement to furnish information Condition 10: Penalty, Suspension, Surrender, Termination/Revocation of License Condition 11: Actions pursuant to Termination of License Condition 12: Force-Majeure Condition 13: Set Off Condition 14: Way Leave Condition 15: Dispute Settlement Condition 16: Other Conditions

==========================================================================================
Candidate 17
Document: dot_unified_licence_agreement.txt
Paragraph: 216
Keyword hint: Indemnification
Already labelled: nan
Length: 486

FULL CLAUSE TEXT:

6.2 The Licensor shall have the right to direct the Licensee to warn, penalize or terminate the services of the franchisee or agent or distributor servant, after considering any report of conduct or antecedents detrimental to the security of the nation. The decision of the Licensor in this regard shall be final and binding and in any case the Licensee shall bear all liabilities in the matter and keep the Licensor indemnified for all claims, cost, charges or damages in this respect.

==========================================================================================
Candidate 18
Document: dot_unified_licence_agreement.txt
Paragraph: 218
Keyword hint: Non-Compete
Already labelled: nan
Length: 1464

FULL CLAUSE TEXT:

6.4 Further, the Licensee may transfer or assign the License Agreement with prior written approval of the Licensor, in the following circumstances, and if otherwise, no compromise in competition occurs in the provisions of Telecom Services:(i)(a) When transfer or assignment is requested in accordance with the terms and conditions on fulfillment of procedures of Tripartite Agreement if already executed amongst the Licensor, Licensee and Lenders; or (i)(b) Whenever amalgamation or restructuring i.e. merger or demerger is sanctioned and approved by the High Court or Tribunal as per the law in force; in accordance with the provisions; more particularly Sections 391 to 394 of Companies Act, 1956; provided that scheme of amalgamation or restructuring is formulated in such a manner that it shall be effective only after the written approval of the Licensor for transfer/merger of Licenses, and (ii) Prior written consent/No Objection of the Licensor has been obtained for transfer or merger of Licenses as per applicable guidelines issued from time to time. Further, the transferee/assignee is fully eligible in accordance with eligibility criteria as applicable for grant of fresh License in that area and show its willingness in writing to comply with the terms and conditions of the License agreement including past and future roll out obligations as well as to comply with guidelines for transfer/merger of Licenses including for charges as applicable; and

==========================================================================================
Candidate 19
Document: himachal_hemodialysis_ppp_concession_agreement.txt
Paragraph: 499
Keyword hint: Indemnification
Already labelled: nan
Length: 271

FULL CLAUSE TEXT:

Shall be liable for and shall indemnify, protect, defend and hold harmless Concessioning Authority, Concessioning Authority’s officers, SH&FWS, employees and agents from and against any and all demands, claims, suits and causes of action and any and all liability, costs,

==========================================================================================
Candidate 20
Document: mea_pmc_services_agreement.txt
Paragraph: 175
Keyword hint: Force Majeure
Already labelled: nan
Length: 295

FULL CLAUSE TEXT:

a) This AGREEMENT shall without prejudice to the provision of Section 11 (Force Majeure) and Section 14 (Termination) remains in force till the successful commissioning of the project which is expected as per the contractor’s work i.e. 8 months or till completion of the work whichever is later.

In [35]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"
path = INDIAN / "category_review.csv"

review = pd.read_csv(path)

# Normalize review columns to avoid pandas dtype warnings
for col in ["verified_category", "include_in_testset", "review_notes"]:
    review[col] = review[col].fillna("").astype(str)

labels = {
    10: ("Penalties", "yes", "Liquidated damages for delayed delivery"),
    11: ("Force Majeure", "yes", "Allocation of losses from force majeure"),
    12: ("Termination", "no", "Contract duration; overlaps with candidate 20"),
    13: ("Commercial Terms", "no", "Contract-period extension"),
    14: ("Confidentiality", "yes", "Restrictions on disclosure of confidential information"),
    15: ("Other", "no", "Table of contents, not a substantive clause"),
    16: ("Indemnification", "yes", "Licensee indemnifies the licensor"),
    17: ("Assignment", "yes", "Transfer and assignment of licence agreement"),
    18: ("Indemnification", "no", "Clause text appears truncated; verify complete source"),
    19: ("Termination", "no", "Contract duration; overlaps with candidate 13"),
}

for idx, (category, include, note) in labels.items():
    review.loc[idx, "verified_category"] = category
    review.loc[idx, "include_in_testset"] = include
    review.loc[idx, "review_notes"] = note

review.to_csv(path, index=False)

print("Saved:", path)
print("Total labelled:", review["verified_category"].ne("").sum())
print("Included:", (review["include_in_testset"] == "yes").sum())
print("Excluded:", (review["include_in_testset"] == "no").sum())

display(review.loc[10:19, [
    "verified_category", "include_in_testset", "review_notes"
]])

Saved: /kaggle/working/indian_eval_project/indian_set/category_review.csv
Total labelled: 20
Included: 12
Excluded: 8

,verified_category,include_in_testset,review_notes
10,Penalties,yes,Liquidated damages for delayed delivery
11,Force Majeure,yes,Allocation of losses from force majeure
12,Termination,no,Contract duration; overlaps with candidate 20
13,Commercial Terms,no,Contract-period extension
14,Confidentiality,yes,Restrictions on disclosure of confidential inf...
15,Other,no,"Table of contents, not a substantive clause"
16,Indemnification,yes,Licensee indemnifies the licensor
17,Assignment,yes,Transfer and assignment of licence agreement
18,Indemnification,no,Clause text appears truncated; verify complete...
19,Termination,no,Contract duration; overlaps with candidate 13

In [36]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review = pd.read_csv(INDIAN / "category_review.csv")

for i in range(20, min(30, len(review))):
    row = review.iloc[i]

    print("\n" + "=" * 90)
    print(f"Candidate {i + 1}")
    print("Document:", row["document_file"])
    print("Paragraph:", row["paragraph_no"])
    print("Keyword hint:", row["category_hint"])
    print("Length:", len(str(row["clause_text"])))
    print("\nFULL CLAUSE TEXT:\n")
    print(row["clause_text"])

==========================================================================================
Candidate 21
Document: meity_msa_cloud_services_template.txt
Paragraph: 405
Keyword hint: Penalties
Length: 171

FULL CLAUSE TEXT:

g) Payments shall be subject to the application of liquidated damages or SLA penalties and its adjustments/corrections as may be provided for in the Agreement and the SLA.

==========================================================================================
Candidate 22
Document: stqc_non_disclosure_agreement.txt
Paragraph: 19
Keyword hint: Confidentiality
Length: 1035

FULL CLAUSE TEXT:

(a) The term “Confidential Information” shall include, without limitation, all information and materials, furnished by either Party to the other in connection with Auditee products and services including information transmitted in writing, orally, visually (e.g. video terminal display) or on magnetic media, and including all proprietary information, customer & prospect lists, trade secrets, trade names or proposed trade names, methods and procedures of operation, business or marketing plans, licensed document know-how, ideas, concepts, designs, drawings, flow charts, diagrams, quality manuals, checklists, guidelines, processes, formulae, source code materials, specifications, programs, software packages, codes and other intellectual property relating to Auditee products and services. Results of any information security audits, tests, analysis, extracts or usages carried out by the Auditor in connection with the Auditee’s products and/or services, IT infrastructure, etc. shall also be considered Confidential Information.

==========================================================================================
Candidate 23
Document: noida_airport_concession_agreement.txt
Paragraph: 1206
Keyword hint: Force Majeure
Length: 338

FULL CLAUSE TEXT:

39.7.3, Save and except as expressly provide in this Article 39, neither Party shall be liable in any ‘manner whatsoever tothe other Party in respect of any loss, damage, cost, expense, claims, ‘demands and proceedings relating to or arising out of occurrenceof existence of any Force Majeure Evento exercise of any right pursuant hereto.

==========================================================================================
Candidate 24
Document: noida_airport_concession_agreement.txt
Paragraph: 500
Keyword hint: Force Majeure
Length: 1122

FULL CLAUSE TEXT:

4.1.5. The Parties shall notify each other in writing at least once ina month on the progress made in satisfying the Conditions Precedent. Each Party shall promptly inform the other Paty ‘when any Condition Precedent for which iis responsible as been stisted 4.2.Damages for delay by the Authority Inthe event that (i) the Authority does not procure fulfilment or waiver of any oral ofthe Conditions Precedent set frth in Clause 4.12 within the period speifiedin respect thereof, and (i) the delay has not occured as a result of breach of this Agreement by the Concessionire or due to Force Majeure, the Authority shal pay tothe Concessionte Damages in an amount calculated atthe rate ‘of 0.1% (zero point one percent of the Performance Security for each day’ delay until the Fulfilment ‘of such Conditions Precedent, subject to a maximum amount equal to the Bid Security, 4.3.Damages for delay by the Coneessionaire In the event that (i) the Concessionire does not procure fullilment or waiver of any or all of the ‘Conditions Precedent set forth in Clause 4.1.3 within the period specified in that Clause, and (i) the Ey

==========================================================================================
Candidate 25
Document: noida_airport_concession_agreement.txt
Paragraph: 1385
Keyword hint: Indemnification
Length: 2575

FULL CLAUSE TEXT:

474.1. The Indemnified Party shall have the right, but not the obligation, to contest, defend and litigate any claim, action, suitor proceeding by any third pary alleged or assered against such Party in respect of, resulting from, related to or arising out of any matter for which tis ‘entitled to be indemnified hereunder, and reasonable costs and expenses thereof shall be indemnified by the Indemnifying Party. If the Indemnifying Party acknowledges in writing its obligation to indemnify the Indemnified Party in respect of loss to the full extent provided by this Ancle47, the Indemnifying Party shall be entitled, at its option, toassume and contol the detence of such claim action, suitor proceeding, liabilities, payments and obligations a its expense and through the counsel of its choice: provided it gives prompt notice ofits imation to do so to the Indemnified Party and reimburses the Indemnified Party forthe reasonable cost and expenses incurred by the Indemnified Paty prior ta the assumption by the Indemnifying Party of such defence. The Indemnifying Party shall not be entitled to ste ‘or compromise any claim, demand, action, suit or proceeding without the prior writen ‘consent ofthe Indemnified Party, unless the Indemnifying Paty provides such security othe Indemnified Paty as shal be reasonably required by the Indemnified Party to secure the loss to be indemnified hereunder tothe extent x0 compromised or settled 4742. I the Indemnifying Party has exercised its rights under Clause 473, the Indemnified Panty shall nt be entitled to setle or compromise any claim, action suitor proceeding without the Prior writen consent ofthe Indemnifying Party (which consent shall not be unteasonably withheld or delayed), 4ATA3. the Indemnifying Panty exercises its ights under Clause 47.3, the Indemnified Party shall nevertheless have the right to employ its own counsel, and such counsel may participate in such action, but the fees and expenses of such counsel shall be at the expense of the Indemnified Party, when and as incurted, unless: {the employment of counsel by such party has been authorised in writing by the Indemnifying Pary: the Indemnified Party shall have reasonably concladed that there may be a conflict of interest between the Indemnifying Party and the Indemnified Party inthe conduct of the defence of such action: the Indemnifying Party shall not, in fact have employed independent counsel reasonably satisfactory othe Indemnified Paty to assume the defence of sue action and shall have heenso notified by the Indemnified Party: oF aa

==========================================================================================
Candidate 26
Document: noida_airport_concession_agreement.txt
Paragraph: 2560
Keyword hint: Force Majeure
Length: 984

FULL CLAUSE TEXT:

9 shall apply’ the performanceby any party (the "Affected Party") ofits obligations under this Agreement is prevented, hindered or delayed in wholeor in part by eason of Force Majeure as defined in Schedule 4 Consequences of Force Majeure Performance Obligation The Affected Paty shall not be liable for any failure to comply, or delay in complying, with any ‘obligation underor pursuant to this Agreement anit shall not be required to perform its obligations to the exten that such failure or delay has been caused directly by any event of Force Majeure and, in particular, but without limitation, the time allowed for performance ofany such obligations shall bbe extended accordingly Notification If the Affected Party claims that it has been prevented from fulfilling any of ts obligations under this Agreement by reason of any event of Force Majeure it shall notify the other Parties as son as reasonably practicable in writing, tating the basis fr the claim and the consequences.

==========================================================================================
Candidate 27
Document: aera_rfp_consultant_2025.txt
Paragraph: 189
Keyword hint: Penalties
Length: 255

FULL CLAUSE TEXT:

AERA reserves the right to extend the time period for completion of tariff determination exercise beyond six months, at its sole discretion, without any financial implication to AERA and without imposition of liquidated damages to the selected consultant.

==========================================================================================
Candidate 28
Document: dot_unified_licence_agreement.txt
Paragraph: 498
Keyword hint: Confidentiality
Length: 225

FULL CLAUSE TEXT:

38.3 In case any confidential information is divulged to the LICENSEE for proper implementation of the Agreement, it shall be binding on the LICENSEE and its employees and servants to maintain its secrecy and confidentiality.

==========================================================================================
Candidate 29
Document: dot_unified_licence_agreement.txt
Paragraph: 1726
Keyword hint: Penalties
Length: 220

FULL CLAUSE TEXT:

4.8 For the purpose of calculation of delay in compliance of rollout obligations, the month shall mean 1 Calendar month and any extra day shall be counted as full month for the purposes of recovery of liquidated damages.

==========================================================================================
Candidate 30
Document: dot_unified_licence_agreement.txt
Paragraph: 265
Keyword hint: Force Majeure
Length: 168

FULL CLAUSE TEXT:

12.3 While it will normally not be a ground for non-payment of License Fee, the liability for payment of License fee for such inoperative period(s) due to force majeure

In [38]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"
path = INDIAN / "category_review.csv"

review = pd.read_csv(path)

for col in ["verified_category", "include_in_testset", "review_notes"]:
    review[col] = review[col].fillna("").astype(str)

labels = {
    20: ("Penalties", "yes", "Liquidated damages and SLA penalties"),
    21: ("Confidentiality", "yes", "Definition of confidential information"),
    22: ("Force Majeure", "yes", "Liability relating to force majeure"),
    23: ("Penalties", "yes", "Damages for delayed conditions precedent"),
    24: ("Indemnification", "yes", "Handling and defence of indemnity claims; review length"),
    25: ("Force Majeure", "yes", "Excused performance and notification"),
    26: ("Commercial Terms", "no", "Duplicates earlier contract-extension subject"),
    27: ("Confidentiality", "yes", "Duty to maintain secrecy"),
    28: ("Penalties", "yes", "Calculation of liquidated damages"),
    29: ("Force Majeure", "no", "Incomplete clause text"),
}

for idx, (category, include, note) in labels.items():
    review.loc[idx, "verified_category"] = category
    review.loc[idx, "include_in_testset"] = include
    review.loc[idx, "review_notes"] = note

review.to_csv(path, index=False)

print("Saved:", path)
print("Total labelled:", review["verified_category"].ne("").sum())
print("Included:", (review["include_in_testset"] == "yes").sum())
print("Excluded:", (review["include_in_testset"] == "no").sum())

display(review.loc[20:29, [
    "verified_category", "include_in_testset", "review_notes"
]])

Saved: /kaggle/working/indian_eval_project/indian_set/category_review.csv
Total labelled: 30
Included: 20
Excluded: 10

,verified_category,include_in_testset,review_notes
20,Penalties,yes,Liquidated damages and SLA penalties
21,Confidentiality,yes,Definition of confidential information
22,Force Majeure,yes,Liability relating to force majeure
23,Penalties,yes,Damages for delayed conditions precedent
24,Indemnification,yes,Handling and defence of indemnity claims; revi...
25,Force Majeure,yes,Excused performance and notification
26,Commercial Terms,no,Duplicates earlier contract-extension subject
27,Confidentiality,yes,Duty to maintain secrecy
28,Penalties,yes,Calculation of liquidated damages
29,Force Majeure,no,Incomplete clause text

In [39]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review = pd.read_csv(INDIAN / "category_review.csv")

for i in range(30, min(40, len(review))):
    row = review.iloc[i]

    print("\n" + "=" * 90)
    print(f"Candidate {i + 1}")
    print("Document:", row["document_file"])
    print("Paragraph:", row["paragraph_no"])
    print("Keyword hint:", row["category_hint"])
    print("Length:", len(str(row["clause_text"])))
    print("\nFULL CLAUSE TEXT:\n")
    print(row["clause_text"])

==========================================================================================
Candidate 31
Document: dot_unified_licence_agreement.txt
Paragraph: 435
Keyword hint: Penalties
Length: 650

FULL CLAUSE TEXT:

The LICENSEE shall clearly define the scope of Service to the Subscriber(s) at the time of entering into contract with such Subscriber(s). Licensor shall have right to impose suitable penalty, not limited to a financial penalty, apart from any other actions for breach of this condition. The LICENSEE shall commence the Service on commercial basis only after starting subscriber registration in the manner prescribed. Before commencement of Service in an area, the LICENSEE shall notify and publicize the address where any subscriber can register demand /request for Telecom Service. Any change of this address shall be duly notified by the Licensee.

==========================================================================================
Candidate 32
Document: gem_general_terms_and_conditions.txt
Paragraph: 9
Keyword hint: Penalties
Length: 612

FULL CLAUSE TEXT:

d. SERVICE LEVEL AGREEMENT (SLA)” shall mean the Contractual Commitment that prevails between the Buyer and the Service Provider with regard to type of service to be provided, deliverables, desired performance level, reliability and responsiveness, monitoring process and service level reporting, response and issue resolution time-frame, repercussions / penalties / remedies for service provider not meeting its commitment. The SLA of a particular contract may carry the matrix regarding the delivery of the goods and/or services and the corresponding penalties or remedies and liquidated damages as applicable.

==========================================================================================
Candidate 33
Document: aera_rfp_consultant_2025.txt
Paragraph: 873
Keyword hint: Indemnification
Length: 509

FULL CLAUSE TEXT:

The Consultant shall hold the Authority harmless and indemnified for any losses, claims, damages, expenses (including all legal expenses), awards, penalties or injuries (collectively referred to as “Claims”) which may arise from or due to any unauthorized use of such Consultancy Documents, or due to any breach or failure on part of the Consultant (or any Third Party appointed by the Consultant) to perform any of its duties or obligations in relation to securing the aforementioned rights of the Authority.

==========================================================================================
Candidate 34
Document: aera_rfp_consultant_2025.txt
Paragraph: 854
Keyword hint: Confidentiality
Length: 474

FULL CLAUSE TEXT:

d) is provided to the professional advisers, agents, auditors or representatives of the Consultant or its Key Personnel, as is reasonable under the circumstances; provided, however, that the Consultant or Key Personnel, as the case may be, shall require their professional advisers, agents, auditors or its representatives, to undertake in writing to keep such Confidential Information, confidential and shall use its best efforts to ensure compliance with such undertaking.

==========================================================================================
Candidate 35
Document: stqc_non_disclosure_agreement.txt
Paragraph: 70
Keyword hint: Non-Solicitation
Length: 432

FULL CLAUSE TEXT:

18. Non-solicitation. During the term of this Agreement and thereafter for a further period of two (2) years Auditor shall not solicit or attempt to solicit Auditee’s employees and/or consultants, for the purpose of hiring/contract or to proceed to conduct business similar to Auditee with any employee and/or consultant of the Auditee who has knowledge of the Confidential Information, without the prior written consent of Auditee.

==========================================================================================
Candidate 36
Document: stqc_non_disclosure_agreement.txt
Paragraph: 57
Keyword hint: Confidentiality
Length: 158

FULL CLAUSE TEXT:

shall not disclose such Confidential Information to any affiliates, subsidiaries, associates and/or third party without prior written approval of the Auditee.

==========================================================================================
Candidate 37
Document: stqc_non_disclosure_agreement.txt
Paragraph: 55
Keyword hint: Penalties
Length: 694

FULL CLAUSE TEXT:

In addition, Auditor shall compensate the Auditee for the loss or damages caused to the auditee, actual and liquidated damages, which may be demanded by Auditee with liquidated damages not to exceed the Contract value. Moreover, Auditee shall be entitled to recover all costs of litigation including reasonable attorneys’ fees which it or they may incur in connection with defending its interests and enforcement of contractual rights arising due to a breach of this agreement by Auditor. All rights and remedies hereunder are cumulative and in addition to any other rights or remedies under any applicable law, at equity, or under this Agreement, subject only to any limitations stated herein.

==========================================================================================
Candidate 38
Document: noida_airport_concession_agreement.txt
Paragraph: 1963
Keyword hint: Non-Compete
Length: 2013

FULL CLAUSE TEXT:

Parking of vehicles 1k wll be our endeavour to provide adequate parking space for parking of various vehicles like car, scooter, bus ete. The use of parking facilites will be available on payment of prescribed fees which may vary according tothe vehicles and the typeof parking used It is our aim to ensure that you do not spend more thanS minutes for parkng/aking out your vehicle Length of queue Adequate number of check-in counters, xray baggage machines, conveyor belts ete provided so thatthe time spent on qucues is kept at minimum, Facilities ‘You are eniledto fre facilis like toilets, clean drinking water, liquid soap, paper glass and child ear room. OFcourse, ll oter facilities wil be available on payment basis. All dhe essential facilis for eating, drinking and shopping for travellers’ need, wil be available ina pleasing mosphere. In order to ensure availablity of reasonably priced basic beverages and food items, vending machines would be installed at convenient locations. We will ensure thatthe vendors price their items, a per laws relating to MRP. Vending machines of competing vendors wil be provided to ensure competition and choice tothe passengers, We will also ensure the cleanliness tnd hygiene of the Terminal Building so that you spend your time in a related and pleasant (Our target wil be to ensure that you do not have to stand ina queue for more than S minutes for ios of the services and not more than 20 minutes for your luggage baggage, Seating The wait ag arca forthe users willbe so planned as to ensure that at least 30% of the peak hour capaci are provided comfortable seats Adequate lighting will be provided for your comfort and the temperature inside the Terminal Building willbe maintained at 25° C when the outside temperature is below 40" Inother cases the difference between the temperature outside the Terminal Building and the temperature inside the Terminal Building will not be less than 15° C. During winter season, the temperature shall rot be less than 15°C.

==========================================================================================
Candidate 39
Document: mha_rfp_project_management_consultants.txt
Paragraph: 531
Keyword hint: Confidentiality
Length: 917

FULL CLAUSE TEXT:

All information (whether written/ tangible or oral/ Intangible) furnished by the Purchaser or any third party to the Bidder or Bidder’s Representatives/ employees/ agents, in connection with this Contract, and all analyses, compilations, studies or other information documents or materials prepared by Bidder or Bidder’s Representatives/ employees/ agents etc., in relation to information obtained by the Bidder in connection to and under the purview of this Contract shall be considered Confidential Information.The Bidder shall not, either during the term or after expiration of this Contract, disclose any proprietary or confidential information relating to the Services/Contract and/or Purchaser’s business/ operations, information, Application/software, hardware, business data, architecture schematics, designs, storage media and other information / documents without the prior written consent of the Purchaser.

==========================================================================================
Candidate 40
Document: mha_rfp_project_management_consultants.txt
Paragraph: 608
Keyword hint: Confidentiality
Length: 178

FULL CLAUSE TEXT:

5. The Bidder shall establish and maintain appropriate security measures to provide for the safe custody of the Confidential Information and to prevent unauthorised access to it.

In [40]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"
path = INDIAN / "category_review.csv"

review = pd.read_csv(path)

for col in ["verified_category", "include_in_testset", "review_notes"]:
    review[col] = review[col].fillna("").astype(str)

labels = {
    30: ("Penalties", "yes", "Penalty for failure to define service scope"),
    31: ("Commercial Terms", "yes", "SLA commitments and remedies"),
    32: ("Indemnification", "yes", "Indemnity for unauthorised use and breach"),
    33: ("Confidentiality", "yes", "Disclosure to professional advisers"),
    34: ("Non-Solicitation", "yes", "Restriction on soliciting employees and consultants"),
    35: ("Confidentiality", "yes", "Restriction on unauthorised disclosure"),
    36: ("Penalties", "yes", "Damages and litigation costs after breach"),
    37: ("Other", "no", "Passenger facilities and service standards"),
    38: ("Confidentiality", "yes", "Definition and protection of confidential information"),
    39: ("Confidentiality", "yes", "Security measures for confidential information"),
}

for idx, (category, include, note) in labels.items():
    review.loc[idx, "verified_category"] = category
    review.loc[idx, "include_in_testset"] = include
    review.loc[idx, "review_notes"] = note

review.to_csv(path, index=False)

print("Saved:", path)
print("Total labelled:", review["verified_category"].ne("").sum())
print("Included:", (review["include_in_testset"] == "yes").sum())
print("Excluded:", (review["include_in_testset"] == "no").sum())

display(review.loc[30:39, [
    "verified_category", "include_in_testset", "review_notes"
]])

Saved: /kaggle/working/indian_eval_project/indian_set/category_review.csv
Total labelled: 40
Included: 29
Excluded: 11

,verified_category,include_in_testset,review_notes
30,Penalties,yes,Penalty for failure to define service scope
31,Commercial Terms,yes,SLA commitments and remedies
32,Indemnification,yes,Indemnity for unauthorised use and breach
33,Confidentiality,yes,Disclosure to professional advisers
34,Non-Solicitation,yes,Restriction on soliciting employees and consul...
35,Confidentiality,yes,Restriction on unauthorised disclosure
36,Penalties,yes,Damages and litigation costs after breach
37,Other,no,Passenger facilities and service standards
38,Confidentiality,yes,Definition and protection of confidential info...
39,Confidentiality,yes,Security measures for confidential information

In [41]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review = pd.read_csv(INDIAN / "category_review.csv")

for i in range(40, len(review)):
    row = review.iloc[i]

    print("\n" + "=" * 90)
    print(f"Candidate {i + 1}")
    print("Document:", row["document_file"])
    print("Paragraph:", row["paragraph_no"])
    print("Keyword hint:", row["category_hint"])
    print("Length:", len(str(row["clause_text"])))
    print("\nFULL CLAUSE TEXT:\n")
    print(row["clause_text"])

==========================================================================================
Candidate 41
Document: meity_msa_cloud_services_template.txt
Paragraph: 594
Keyword hint: Confidentiality
Length: 209

FULL CLAUSE TEXT:

The Managed Service Provider shall keep confidential all the details and information with regard to the Project, including systems, facilities, operations, management and maintenance of the systems/facilities.

==========================================================================================
Candidate 42
Document: mha_rfp_project_management_consultants.txt
Paragraph: 422
Keyword hint: Penalties
Length: 700

FULL CLAUSE TEXT:

The Bidder shall ensure that none of the Key Personnel (refer Clause 10.2 of Section 5 of the RFP) proposed, exit from the project during first 18 months of the project. The change of Key Personnel will be accepted only in case of person leaving the organization or medical exigency. It is important that the Bidder submits profiles of only those resources that are available for the project. In case of any change of the Key Personnel during the first 18 months of the project, it would attract a penalty as per clause 39 in this Section irrespective of the reasons. It does not apply in case of change requested by the Purchaser. Every change in any case will require the approval of the Purchaser.

==========================================================================================
Candidate 43
Document: meity_msa_cloud_services_template.txt
Paragraph: 384
Keyword hint: Confidentiality
Length: 394

FULL CLAUSE TEXT:

c) The Parties to the Agreement shall use reasonable endeavors to report forthwith in writing to each other all identified attempts (whether successful or not) by unauthorized persons (including unauthorized persons who are employees of any Party) either to gain access to or interfere with the Purchaser as the case may be or any of their nominees data, facilities or Confidential Information.

==========================================================================================
Candidate 44
Document: noida_airport_concession_agreement.txt
Paragraph: 1379
Keyword hint: Indemnification
Length: 1980

FULL CLAUSE TEXT:

47.1.General indemnity aT The Concessionaire shall indemnify, defend, save and hold harmless the Authority and its officers, servants, agents, Government Instrumenalities, Designated GOL Agencies and Authority owned andlor controlled enitieslenterprises, (the “Government Indemnified Persons") against any and all suits, proceedings, actions, demands and claims from third parties for any loss, damage, cost and expense of whatever kind and nature, whether arising ‘at of any breach by the Concessionaire of any of is obligations under his Agreement or any related agrcement or on account of any defect or deficiency in the provision of services by the Concessionaie tothe Authority orany User or from any negligence of the Concessionaire under contrat or tort, or on anyother ground whatsoever, except tothe extent that any such suits, proceedings, actions, demands and claims have arisen due to any negligent act oF ‘omission, or breach or default ofthis Agreement on the part of the Government Indemnified Persons 4712. The Authority shall indemnify, defend, save and hold harmless the Concessionare against any and all sis, proceedings, actions, demands and claims from thir parties for any loss, ‘damage, cost and expense of whatever kind and nature arising out of (a) defect in ttle and/or the ight ofthe Authority inthe land comprised in the Sit, andr (b) breach by the Authority ‘of any ofits obligations under this Agreement or any related agreement, which materially and adversely affect the performance by the Concessionsire of its obligations under this Agreement, save and except that where any such claim, suit, proceeding, action, and/or ‘demand has arisen duc toa negligent actor omission or breach of anyof its obligations under any provision ofthis Agreement or any related agreement andor breach of its statutory duty ‘on the par of the Concessionaite, its asigns, affiliates, contractors, servants or agents, the same shall be the liability of the Concessions.

==========================================================================================
Candidate 45
Document: meity_msa_cloud_services_template.txt
Paragraph: 575
Keyword hint: Confidentiality
Length: 295

FULL CLAUSE TEXT:

The Managed Service Provider shall report to the Purchaser, in writing, of information security breaches by unauthorized persons (including unauthorized persons who are employees of any Party) either to gain access to or interfere with the Project's Data, facilities or Confidential Information.

In [42]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"
path = INDIAN / "category_review.csv"

review = pd.read_csv(path)

for col in ["verified_category", "include_in_testset", "review_notes"]:
    review[col] = review[col].fillna("").astype(str)

labels = {
    40: ("Confidentiality", "yes", "Protection of project information"),
    41: ("Penalties", "yes", "Penalty for changing key personnel"),
    42: ("Confidentiality", "yes", "Reporting unauthorised access attempts"),
    43: ("Indemnification", "yes", "General indemnity obligations of both parties"),
    44: ("Confidentiality", "yes", "Reporting information-security breaches"),
}

for idx, (category, include, note) in labels.items():
    review.loc[idx, "verified_category"] = category
    review.loc[idx, "include_in_testset"] = include
    review.loc[idx, "review_notes"] = note

review.to_csv(path, index=False)

print("Saved:", path)
print("Total labelled:", review["verified_category"].ne("").sum())
print("Included:", (review["include_in_testset"] == "yes").sum())
print("Excluded:", (review["include_in_testset"] == "no").sum())

print("\nCategory counts among included candidates:")
display(
    review[review["include_in_testset"] == "yes"]
    ["verified_category"]
    .value_counts()
    .rename_axis("category")
    .reset_index(name="count")
)

Saved: /kaggle/working/indian_eval_project/indian_set/category_review.csv
Total labelled: 45
Included: 34
Excluded: 11

Category counts among included candidates:

           category  count
0   Confidentiality     10
1         Penalties      9
2   Indemnification      7
3     Force Majeure      5
4        Assignment      1
5  Commercial Terms      1
6  Non-Solicitation      1

In [43]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

review = pd.read_csv(INDIAN / "category_review.csv").fillna("")
original = pd.read_csv(INDIAN / "clauses.csv").fillna("")

# Select only manually reviewed candidates marked for inclusion
accepted = review[
    review["include_in_testset"].astype(str).str.lower().eq("yes")
].copy()

accepted = accepted.rename(columns={
    "verified_category": "category",
    "review_notes": "source_note"
})

accepted = accepted[
    ["document_file", "category", "clause_text", "source_note"]
]

# Combine with the two original annotations
final_df = pd.concat(
    [
        original[["document_file", "category", "clause_text", "source_note"]],
        accepted
    ],
    ignore_index=True
)

# Flag exact duplicate clauses for review
final_df["normalized_text"] = (
    final_df["clause_text"]
    .astype(str)
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

print("Original annotations:", len(original))
print("Accepted candidates:", len(accepted))
print("Combined rows:", len(final_df))
print("Exact duplicate texts:", final_df["normalized_text"].duplicated().sum())

print("\nCategory distribution:")
display(
    final_df["category"]
    .value_counts()
    .rename_axis("category")
    .reset_index(name="count")
)

out = INDIAN / "clauses_expanded_draft.csv"
final_df.drop(columns=["normalized_text"]).to_csv(out, index=False)

print("\nSaved draft:", out)

Original annotations: 2
Accepted candidates: 34
Combined rows: 36
Exact duplicate texts: 0

Category distribution:

           category  count
0   Confidentiality     11
1         Penalties      9
2   Indemnification      8
3     Force Majeure      5
4        Assignment      1
5  Commercial Terms      1
6  Non-Solicitation      1

Saved draft: /kaggle/working/indian_eval_project/indian_set/clauses_expanded_draft.csv

In [44]:
import pandas as pd
from pathlib import Path
from difflib import SequenceMatcher

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

df = pd.read_csv(INDIAN / "clauses_expanded_draft.csv").fillna("")

# 1. Check category compatibility
allowed = {
    "Assignment", "Commercial Terms", "Dispute Resolution",
    "Governing Law / Jurisdiction", "Intellectual Property",
    "Liability", "Non-Compete", "Non-Solicitation", "Other",
    "Penalties", "Termination", "Warranty", "Confidentiality",
    "Force Majeure", "Indemnification", "Modification",
    "Payment", "Privacy / Data Protection"
}

print("Unsupported categories:")
print(sorted(set(df["category"]) - allowed))

# 2. Find highly similar clauses (manual review required)
texts = (
    df["clause_text"].astype(str)
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .tolist()
)

pairs = []
for i in range(len(texts)):
    for j in range(i + 1, len(texts)):
        score = SequenceMatcher(None, texts[i], texts[j]).ratio()
        if score >= 0.75:
            pairs.append({
                "row_a": i,
                "row_b": j,
                "similarity": round(score, 3),
                "category_a": df.iloc[i]["category"],
                "category_b": df.iloc[j]["category"],
                "document_a": df.iloc[i]["document_file"],
                "document_b": df.iloc[j]["document_file"]
            })

similar = pd.DataFrame(pairs)
print("\nNear-duplicate pairs (similarity >= 0.75):", len(similar))

if not similar.empty:
    display(similar.sort_values("similarity", ascending=False))
else:
    print("No pairs crossed the similarity threshold.")

Unsupported categories:
[]

Near-duplicate pairs (similarity >= 0.75): 0
No pairs crossed the similarity threshold.

In [45]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

df = pd.read_csv(INDIAN / "clauses_expanded_draft.csv").fillna("")

for idx in [1, 24]:
    row = df.iloc[idx]

    print("\n" + "=" * 80)
    print("Row:", idx)
    print("Document:", row["document_file"])
    print("Category:", row["category"])
    print("Source note:", row["source_note"])
    print("Length:", len(row["clause_text"]))
    print("\nClause text:\n")
    print(row["clause_text"])

================================================================================
Row: 1
Document: aera_rfp_consultant_2025.txt
Category: Indemnification
Source note: AERA agreement; clause 3.6.4
Length: 3046

Clause text:

3.6.4

The Consultant shall hold the Authority harmless and indemnified for any losses, claims, damages, expenses (including all legal expenses), awards, penalties or injuries (collectively referred to as “Claims”) which may arise from or due to any unauthorized use of such Consultancy Documents, or due to any breach or failure on part of the Consultant (or any Third Party appointed by the Consultant) to perform any of its duties or obligations in relation to securing the aforementioned rights of the Authority.

3.7

Materials furnished by the Authority Materials made available to the Consultant by the Authority shall be the property of the Authority and shall be marked accordingly. Upon termination or expiration of this Agreement, the Consultant shall furnish forthwith to the Authority, an inventory of such materials and shall dispose of such materials in accordance with the instructions of the Authority. The Consultant would be allowed to retain a copy of its working papers to maintain a professional record of its involvement in the engagement and to comply with applicable legal and regulatory requirements. Also, it is appreciated that it may not be possible for the Consultant to permanently dispose-off all information so furnished (for instance in terms of information embodied in project related emails). In all cases, the Consultant shall be responsible for not using such information for purposes unrelated to this Agreement without the prior written approval of the Authority.

3.8

Accuracy of Documents The Consultant shall be responsible for accuracy of the documents drafted and/ or vetted and data collected by it directly or procured from other agencies/ authorities, estimates and all other details prepared by it as part of these services. Subject to the provisions of Clause 3.4, it shall indemnify the Authority against any inaccuracy in its work which might surface during the currency of the assignment [i.e., till completion of milestone/ activity 4 as given in clause 2.4(d) of the RFP], if such inaccuracy is the result of any negligence or inadequate due diligence on part of the Consultant or arises out of its failure to conform to good industry practice. The Consultant shall also be responsible for promptly correcting, at its own cost and risk, the documents including any re-survey / investigations, during the said period.

3.9

Providing access to the Consultant Office and Key Personnel The Consultant shall ensure that the Authority, and, officials of the Authority having authorization from the Authority, are allowed to visit, if required, to the Consultant’s Office and interact with the Key Personnel during office hours.

4.

CONSULTANT’s KEY PERSONNEL

4.1

General The Consultant shall employ and provide such qualified and experienced Key Personnel as may be required to carry out the Services.

4.2

Deployment of Key Personnel A list of Key Personnel deployed for this contract is placed at Annexure – I of this Agreement.

4.3 5.

5.1

Substitution of Key Personnel: As per clause 4

================================================================================
Row: 24
Document: aera_rfp_consultant_2025.txt
Category: Indemnification
Source note: Indemnity for unauthorised use and breach
Length: 509

Clause text:

The Consultant shall hold the Authority harmless and indemnified for any losses, claims, damages, expenses (including all legal expenses), awards, penalties or injuries (collectively referred to as “Claims”) which may arise from or due to any unauthorized use of such Consultancy Documents, or due to any breach or failure on part of the Consultant (or any Third Party appointed by the Consultant) to perform any of its duties or obligations in relation to securing the aforementioned rights of the Authority.

In [46]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

draft_path = INDIAN / "clauses_expanded_draft.csv"
df = pd.read_csv(draft_path).fillna("")

# Remove the duplicate shortlist entry at row index 24.
# Keep the original annotation at row index 1.
clean = df.drop(index=24).reset_index(drop=True)

out = INDIAN / "clauses_expanded_clean.csv"
clean.to_csv(out, index=False)

print("Rows before:", len(df))
print("Rows after:", len(clean))
print("Saved:", out)

print("\nCategory distribution:")
display(
    clean["category"].value_counts()
    .rename_axis("category")
    .reset_index(name="count")
)

Rows before: 36
Rows after: 35
Saved: /kaggle/working/indian_eval_project/indian_set/clauses_expanded_clean.csv

Category distribution:

           category  count
0   Confidentiality     11
1         Penalties      9
2   Indemnification      7
3     Force Majeure      5
4        Assignment      1
5  Commercial Terms      1
6  Non-Solicitation      1

In [47]:
import sys
import subprocess
import os
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

env = os.environ.copy()
env["PYTHONPATH"] = (
    str(WORK) + os.pathsep
    + str(INDIAN) + os.pathsep
    + env.get("PYTHONPATH", "")
)

result = subprocess.run(
    [sys.executable, str(INDIAN / "build_indian_testset.py"), "--help"],
    capture_output=True,
    text=True,
    env=env
)

print(result.stdout)
if result.stderr:
    print("STDERR:\n", result.stderr)

print("\nClean CSV columns:")
import pandas as pd
clean = pd.read_csv(INDIAN / "clauses_expanded_clean.csv")
print(clean.columns.tolist())
print("Rows:", len(clean))

usage: build_indian_testset.py [-h] [--docs_dir DOCS_DIR]
                               [--clauses_csv CLAUSES_CSV] [--out_dir OUT_DIR]
                               [--make_template DIR] [--list_categories]

build_indian_testset.py -- turn your hand-collected Indian clauses into a test set
the Phase 3 code can evaluate.

YOU PROVIDE
    indian_set/documents/*.txt   full plain text of each Indian agreement / template
    indian_set/clauses.csv       one row per clause you picked
        document_file   file name inside documents/ (e.g. nda_sample_1.txt)
        category        one of the 18 ClauseXplain categories (exact spelling, see --list_categories)
        clause_text     the clause, COPIED from that document (whitespace differences are fine)
        source_note     where the document came from (public template, tender, ...)

THIS SCRIPT
    finds each clause inside its document (so we get exact character offsets, which
    the span evaluation needs), and writes
        built/indian_mapped.jsonl      same format as clauses_mapped.jsonl
        built/indian_contracts.json    {contract_id: full text}
        built/build_report.md          counts, problems, coverage warnings

    python build_indian_testset.py --make_template indian_set      # starter folder + CSV
    python build_indian_testset.py --docs_dir indian_set/documents --clauses_csv indian_set/clauses.csv --out_dir indian_set/built

GUIDANCE FOR COLLECTING (so the set is honest)
    * Use documents you are allowed to use (public templates, government tender
      documents, sample agreements). Do not include confidential or personal data.
    * Pick clauses by CATEGORY MEANING, before looking at what any model predicts.
    * Aim for 3+ clauses per category you can cover, 30-50 in total, from several
      different documents.  Some categories (Confidentiality, Indemnification,
      Payment, Force Majeure, Modification, Privacy) are valuable to include: the
      model has never seen them, and the report will say so.
    * If a clause could fit two categories, choose the closest and add a source_note.

options:
  -h, --help            show this help message and exit
  --docs_dir DOCS_DIR
  --clauses_csv CLAUSES_CSV
  --out_dir OUT_DIR
  --make_template DIR   create DIR/documents and DIR/clauses.csv
  --list_categories


Clean CSV columns:
['document_file', 'category', 'clause_text', 'source_note']
Rows: 35

In [48]:
import os
import sys
import subprocess
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

env = os.environ.copy()
env["PYTHONPATH"] = (
    str(WORK) + os.pathsep
    + str(INDIAN) + os.pathsep
    + env.get("PYTHONPATH", "")
)

cmd = [
    sys.executable,
    str(INDIAN / "build_indian_testset.py"),
    "--docs_dir", str(INDIAN / "documents"),
    "--clauses_csv", str(INDIAN / "clauses_expanded_clean.csv"),
    "--out_dir", str(INDIAN / "built_expanded")
]

result = subprocess.run(
    cmd,
    capture_output=True,
    text=True,
    env=env
)

print(result.stdout)
if result.stderr:
    print("STDERR:\n", result.stderr)

print("Return code:", result.returncode)

# Indian test set build report

32 clauses from 9 documents.

| Category | clauses | model has training data? |
|---|---|---|
| Assignment | 1 | yes |
| Commercial Terms | 1 | yes |
| Non-Solicitation | 1 | yes |
| Penalties | 9 | yes |
| Confidentiality | 9 | no (never seen in training) |
| Force Majeure | 5 | no (never seen in training) |
| Indemnification | 6 | no (never seen in training) |

Categories with fewer than 3 clauses (too thin for per-category scores): Assignment, Commercial Terms, Non-Solicitation

CSV encoding read as: utf-8

## Clauses per document

- noida_airport_concession_agreement.txt: 7  <-- more than 6; one document may dominate
- dot_unified_licence_agreement.txt: 6
- aera_rfp_consultant_2025.txt: 4
- meity_msa_cloud_services_template.txt: 4
- stqc_non_disclosure_agreement.txt: 4
- mha_rfp_project_management_consultants.txt: 3
- gem_general_terms_and_conditions.txt: 2
- mea_pmc_services_agreement.txt: 1
- himachal_hemodialysis_ppp_concession_agreement.txt: 1

Clauses in never-seen categories: 20 of 32
NOTE: Dispute Resolution is only 'seen' via CUAD's Covenant Not To Sue (no arbitration/forum clauses), so score it separately from the other seen categories.

## Warnings (rows kept, but check them)
- line 3: text ends in dot leaders or a page number -- probably a table-of-contents line

## Problems (these rows were skipped)
- line 8: DUPLICATE/overlapping row for the same category as line 3; skipped so it is not double counted
- line 13: DUPLICATE/overlapping row for the same category as line 2; skipped so it is not double counted
- line 26: DUPLICATE/overlapping row for the same category as line 2; skipped so it is not double counted

Return code: 0

In [49]:
from pathlib import Path
import pandas as pd

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

report_path = INDIAN / "built_expanded" / "build_report.md"
csv_path = INDIAN / "clauses_expanded_clean.csv"

print(report_path.read_text(encoding="utf-8"))

df = pd.read_csv(csv_path).fillna("")

print("\nRows mentioned in the builder warnings:")
display(df.loc[[12, 25], [
    "document_file", "category", "source_note", "clause_text"
]])

# Indian test set build report

32 clauses from 9 documents.

| Category | clauses | model has training data? |
|---|---|---|
| Assignment | 1 | yes |
| Commercial Terms | 1 | yes |
| Non-Solicitation | 1 | yes |
| Penalties | 9 | yes |
| Confidentiality | 9 | no (never seen in training) |
| Force Majeure | 5 | no (never seen in training) |
| Indemnification | 6 | no (never seen in training) |

Categories with fewer than 3 clauses (too thin for per-category scores): Assignment, Commercial Terms, Non-Solicitation

CSV encoding read as: utf-8

## Clauses per document

- noida_airport_concession_agreement.txt: 7  <-- more than 6; one document may dominate
- dot_unified_licence_agreement.txt: 6
- aera_rfp_consultant_2025.txt: 4
- meity_msa_cloud_services_template.txt: 4
- stqc_non_disclosure_agreement.txt: 4
- mha_rfp_project_management_consultants.txt: 3
- gem_general_terms_and_conditions.txt: 2
- mea_pmc_services_agreement.txt: 1
- himachal_hemodialysis_ppp_concession_agreement.txt: 1

Clauses in never-seen categories: 20 of 32
NOTE: Dispute Resolution is only 'seen' via CUAD's Covenant Not To Sue (no arbitration/forum clauses), so score it separately from the other seen categories.

## Warnings (rows kept, but check them)
- line 3: text ends in dot leaders or a page number -- probably a table-of-contents line

## Problems (these rows were skipped)
- line 8: DUPLICATE/overlapping row for the same category as line 3; skipped so it is not double counted
- line 13: DUPLICATE/overlapping row for the same category as line 2; skipped so it is not double counted
- line 26: DUPLICATE/overlapping row for the same category as line 2; skipped so it is not double counted

Rows mentioned in the builder warnings:

,document_file,category,source_note,clause_text
12,dot_unified_licence_agreement.txt,Indemnification,Licensee indemnifies the licensor,6.2 The Licensor shall have the right to direc...
25,stqc_non_disclosure_agreement.txt,Non-Solicitation,Restriction on soliciting employees and consul...,18. Non-solicitation. During the term of this ...

In [50]:
import pandas as pd
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

df = pd.read_csv(INDIAN / "clauses_expanded_clean.csv").fillna("")

for skipped_idx in [12, 25]:
    skipped = df.iloc[skipped_idx]
    print(f"\n{'='*80}")
    print(f"SKIPPED ROW — CSV index {skipped_idx}")
    print("Document:", skipped["document_file"])
    print("Category:", skipped["category"])
    print("Source note:", skipped["source_note"])
    print("Clause:", skipped["clause_text"][:1200])

    same_category = df[
        (df["category"] == skipped["category"]) &
        (df.index < skipped_idx)
    ]

    print("\nEarlier clauses with the same category:")
    for idx, row in same_category.iterrows():
        print(f"\nCSV index {idx} | {row['document_file']}")
        print("Source note:", row["source_note"])
        print("Clause:", row["clause_text"][:1200])

================================================================================
SKIPPED ROW — CSV index 12
Document: dot_unified_licence_agreement.txt
Category: Indemnification
Source note: Licensee indemnifies the licensor
Clause: 6.2 The Licensor shall have the right to direct the Licensee to warn, penalize or terminate the services of the franchisee or agent or distributor servant, after considering any report of conduct or antecedents detrimental to the security of the nation. The decision of the Licensor in this regard shall be final and binding and in any case the Licensee shall bear all liabilities in the matter and keep the Licensor indemnified for all claims, cost, charges or damages in this respect.

Earlier clauses with the same category:

CSV index 1 | aera_rfp_consultant_2025.txt
Source note: AERA agreement; clause 3.6.4
Clause: 3.6.4

The Consultant shall hold the Authority harmless and indemnified for any losses, claims, damages, expenses (including all legal expenses), awards, penalties or injuries (collectively referred to as “Claims”) which may arise from or due to any unauthorized use of such Consultancy Documents, or due to any breach or failure on part of the Consultant (or any Third Party appointed by the Consultant) to perform any of its duties or obligations in relation to securing the aforementioned rights of the Authority.

3.7

Materials furnished by the Authority Materials made available to the Consultant by the Authority shall be the property of the Authority and shall be marked accordingly. Upon termination or expiration of this Agreement, the Consultant shall furnish forthwith to the Authority, an inventory of such materials and shall dispose of such materials in accordance with the instructions of the Authority. The Consultant would be allowed to retain a copy of its working papers to maintain a professional record of its involvement in the engagement and to comply with applicable legal and regulatory requirements. Also, it is appreciated that it may not be possible for the Consultant to

CSV index 5 | noida_airport_concession_agreement.txt
Source note: Intellectual property infringement indemnity
Clause: Without limiting the generality ofthe provisions of this Article 47, the Concessionaire shall fully indemnify, hold harmless and defend the Government Indemnified Persons from and against any and all suis, proceedings, actions, claims, demands, liabilities and damages Which the Government Indemnified Persons may herealter suffer, or pay by reason of any ‘demands, claims, suits or proceedings arising oat of claims of infingement of any domestic for foreign patent sighs, copyrights or other intellectual property. proprietary or <confidemality rights with respect to any materials, information, design or process used by the Concessionaize or by the Concessionare's Contractors in performing the ‘Concessionare's obligations orn any way incorporated in or related to the Project. fn any such suit action, claim or proceedings, a temporary restraint order or preliminary injunetion| is granted, the Concessionireshall make every reasonable effort, by giving a satisfactory hond or otherwise, to secure the revocation or suspension ofthe injunction or restraint onder.

CSV index 6 | aera_rfp_consultant_2025.txt
Source note: Indemnity for inaccurate work
Clause: Accuracy of Documents The Consultant shall be responsible for accuracy of the documents drafted and/ or vetted and data collected by it directly or procured from other agencies/ authorities, estimates and all other details prepared by it as part of these services. Subject to the provisions of Clause 3.4, it shall indemnify the Authority against any inaccuracy in its work which might surface during the currency of the assignment [i.e., till completion of milestone/ activity 4 as given in clause 2.4(d) of the RFP], if such inaccuracy is the result of any negligence or inadequate due diligence on part of the Consultant or arises out of its failure to conform to good industry practice. The Consultant shall also be responsible for promptly correcting, at its own cost and risk, the documents including any re-survey / investigations, during the said period.

CSV index 7 | dot_unified_licence_agreement.txt
Source note: Licensor indemnity
Clause: 30.10 Any dispute, with regard to the provision of Service shall be a matter only between the aggrieved party and the Licensee, who shall duly notify this to all before providing the Service. And in no case, the Licensor shall bear any liability or responsibility in the matter. The LICENSEE shall keep the Licensor indemnified for all claims, cost, charges or damages in the matter.

================================================================================
SKIPPED ROW — CSV index 25
Document: stqc_non_disclosure_agreement.txt
Category: Non-Solicitation
Source note: Restriction on soliciting employees and consultants
Clause: 18. Non-solicitation. During the term of this Agreement and thereafter for a further period of two (2) years Auditor shall not solicit or attempt to solicit Auditee’s employees and/or consultants, for the purpose of hiring/contract or to proceed to conduct business similar to Auditee with any employee and/or consultant of the Auditee who has knowledge of the Confidential Information, without the prior written consent of Auditee.

Earlier clauses with the same category:

In [51]:
from pathlib import Path

INDIAN = Path("/kaggle/working/indian_eval_project/indian_set")
builder = INDIAN / "build_indian_testset.py"

lines = builder.read_text(encoding="utf-8").splitlines()

for i, line in enumerate(lines):
    if "DUPLICATE/overlapping" in line:
        start = max(0, i - 12)
        end = min(len(lines), i + 8)
        print(f"\n--- Lines {start + 1}–{end} ---")
        for j in range(start, end):
            print(f"{j + 1}: {lines[j]}")

--- Lines 107–126 ---
107:             if count > 1:
108:                 multi.append(f"line {n}: text occurs {count} times in {fn}; first occurrence used")
109:             s, e = loc
110:             if len(txt.split()) < 12:
111:                 notes.append(f"line {n}: only {len(txt.split())} words -- looks like a heading, not a clause (check it is not a table-of-contents line)")
112:             if re.search(r"\.{4,}|\s\d{1,3}\s*$", docs[fn][s:e]):
113:                 notes.append(f"line {n}: text ends in dot leaders or a page number -- probably a table-of-contents line")
114:             clash = [(o_fn, o_n, o_cat) for (o_fn, o_s, o_e, o_n, o_cat) in seen_spans
115:                      if o_fn == fn and s < o_e and o_s < e]
116:             if clash:
117:                 same = [c for c in clash if c[2] == cat]
118:                 if same:
119:                     problems.append(f"line {n}: DUPLICATE/overlapping row for the same category as line {same[0][1]}; skipped so it is not double counted")
120:                     continue
121:                 notes.append(f"line {n}: span overlaps line {clash[0][1]} ({clash[0][2]}) but has a different category -- confirm both labels are intended")
122:             seen_spans.append((fn, s, e, n, cat))
123:             cid = slug(fn)
124:             i = per_doc[fn]; per_doc[fn] += 1
125:             rows.append({"clause_id": f"{cid}__{cat}__{i}", "contract_id": cid, "cuad_category": "INDIAN_SET",
126:                          "clausexplain_category": cat, "clause_text": docs[fn][s:e], "char_start": s,

In [52]:
from pathlib import Path

INDIAN = Path("/kaggle/working/indian_eval_project/indian_set")
builder = INDIAN / "build_indian_testset.py"

lines = builder.read_text(encoding="utf-8").splitlines()

for start, end in [(65, 110), (114, 130)]:
    print(f"\n--- Lines {start + 1}–{end} ---")
    for i in range(start, min(end, len(lines))):
        print(f"{i + 1}: {lines[i]}")

--- Lines 66–110 ---
66:     ap.add_argument("--out_dir", default="indian_set/built")
67:     ap.add_argument("--make_template", metavar="DIR", help="create DIR/documents and DIR/clauses.csv")
68:     ap.add_argument("--list_categories", action="store_true")
69:     a = ap.parse_args(argv)
70:
71:     if a.list_categories:
72:         print("\n".join(CATEGORIES)); return
73:     if a.make_template:
74:         d = Path(a.make_template); (d / "documents").mkdir(parents=True, exist_ok=True)
75:         with open(d / "clauses.csv", "w", newline="", encoding="utf-8") as f:
76:             w = csv.writer(f)
77:             w.writerow(["document_file", "category", "clause_text", "source_note"])
78:             w.writerow(["example_nda.txt", "Termination", "Either party may terminate this Agreement by giving thirty (30) days written notice.", "public template (example row, delete me)"])
79:         print(f"created {d}/documents and {d}/clauses.csv; put plain-text agreements in documents/"); return
80:
81:     docs_dir, out = Path(a.docs_dir), Path(a.out_dir)
82:     out.mkdir(parents=True, exist_ok=True)
83:     docs = {p.name: p.read_text(encoding="utf-8", errors="replace") for p in sorted(docs_dir.glob("*.txt"))}
84:     rows, problems, multi = [], [], []
85:     per_doc = Counter()
86:     raw = Path(a.clauses_csv).read_bytes()
87:     try:
88:         csv_text, enc_used = raw.decode("utf-8-sig"), "utf-8"
89:     except UnicodeDecodeError:
90:         csv_text, enc_used = raw.decode("cp1252", errors="replace"), "cp1252 (Excel default; re-save as CSV UTF-8 if text looks wrong)"
91:     import io
92:     seen_spans, per_cat_doc = [], Counter()
93:     notes = []
94:     if True:
95:         f = io.StringIO(csv_text, newline="")
96:         for n, r in enumerate(csv.DictReader(f), start=2):
97:             fn, cat, txt = (r.get("document_file") or "").strip(), (r.get("category") or "").strip(), r.get("clause_text") or ""
98:             if fn.startswith("example_nda"):
99:                 continue
100:             if fn not in docs:
101:                 problems.append(f"line {n}: document '{fn}' not found in {docs_dir}"); continue
102:             if cat not in CATEGORIES:
103:                 problems.append(f"line {n}: category '{cat}' is not one of the 18 (use --list_categories)"); continue
104:             loc, count = locate(docs[fn], txt)
105:             if loc is None:
106:                 problems.append(f"line {n}: clause text not found in {fn}; copy it from the document"); continue
107:             if count > 1:
108:                 multi.append(f"line {n}: text occurs {count} times in {fn}; first occurrence used")
109:             s, e = loc
110:             if len(txt.split()) < 12:

--- Lines 115–130 ---
115:                      if o_fn == fn and s < o_e and o_s < e]
116:             if clash:
117:                 same = [c for c in clash if c[2] == cat]
118:                 if same:
119:                     problems.append(f"line {n}: DUPLICATE/overlapping row for the same category as line {same[0][1]}; skipped so it is not double counted")
120:                     continue
121:                 notes.append(f"line {n}: span overlaps line {clash[0][1]} ({clash[0][2]}) but has a different category -- confirm both labels are intended")
122:             seen_spans.append((fn, s, e, n, cat))
123:             cid = slug(fn)
124:             i = per_doc[fn]; per_doc[fn] += 1
125:             rows.append({"clause_id": f"{cid}__{cat}__{i}", "contract_id": cid, "cuad_category": "INDIAN_SET",
126:                          "clausexplain_category": cat, "clause_text": docs[fn][s:e], "char_start": s,
127:                          "char_end": e, "category_status": "MAPPED", "source": "indian_set",
128:                          "source_note": r.get("source_note", "")})
129:     (out / "indian_mapped.jsonl").write_text("\n".join(json.dumps(r) for r in rows), encoding="utf-8")
130:     used = {r["contract_id"] for r in rows}

In [53]:
from pathlib import Path
import pandas as pd
import json

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

mapped_path = INDIAN / "built_expanded" / "indian_mapped.jsonl"

mapped = [
    json.loads(line)
    for line in mapped_path.read_text(encoding="utf-8").splitlines()
    if line.strip()
]

for filename in [
    "dot_unified_licence_agreement.txt",
    "stqc_non_disclosure_agreement.txt",
]:
    print(f"\n--- {filename} ---")
    for row in mapped:
        if row["contract_id"] == Path(filename).stem:
            print(
                row["clausexplain_category"],
                "start:", row["char_start"],
                "end:", row["char_end"],
                "length:", len(row["clause_text"]),
                "|", row["source_note"]
            )

--- dot_unified_licence_agreement.txt ---

--- stqc_non_disclosure_agreement.txt ---

In [54]:
from pathlib import Path

INDIAN = Path("/kaggle/working/indian_eval_project/indian_set")

report = INDIAN / "built_expanded" / "build_report.md"
mapped = INDIAN / "built_expanded" / "indian_mapped.jsonl"

print("BUILD REPORT")
print(report.read_text(encoding="utf-8"))

print("\nMAPPED FILE EXISTS:", mapped.exists())
if mapped.exists():
    lines = [
        line for line in mapped.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    print("Mapped clause count:", len(lines))
    print("First mapped record:")
    print(lines[0] if lines else "No records")

BUILD REPORT
# Indian test set build report

32 clauses from 9 documents.

| Category | clauses | model has training data? |
|---|---|---|
| Assignment | 1 | yes |
| Commercial Terms | 1 | yes |
| Non-Solicitation | 1 | yes |
| Penalties | 9 | yes |
| Confidentiality | 9 | no (never seen in training) |
| Force Majeure | 5 | no (never seen in training) |
| Indemnification | 6 | no (never seen in training) |

Categories with fewer than 3 clauses (too thin for per-category scores): Assignment, Commercial Terms, Non-Solicitation

CSV encoding read as: utf-8

## Clauses per document

- noida_airport_concession_agreement.txt: 7  <-- more than 6; one document may dominate
- dot_unified_licence_agreement.txt: 6
- aera_rfp_consultant_2025.txt: 4
- meity_msa_cloud_services_template.txt: 4
- stqc_non_disclosure_agreement.txt: 4
- mha_rfp_project_management_consultants.txt: 3
- gem_general_terms_and_conditions.txt: 2
- mea_pmc_services_agreement.txt: 1
- himachal_hemodialysis_ppp_concession_agreement.txt: 1

Clauses in never-seen categories: 20 of 32
NOTE: Dispute Resolution is only 'seen' via CUAD's Covenant Not To Sue (no arbitration/forum clauses), so score it separately from the other seen categories.

## Warnings (rows kept, but check them)
- line 3: text ends in dot leaders or a page number -- probably a table-of-contents line

## Problems (these rows were skipped)
- line 8: DUPLICATE/overlapping row for the same category as line 3; skipped so it is not double counted
- line 13: DUPLICATE/overlapping row for the same category as line 2; skipped so it is not double counted
- line 26: DUPLICATE/overlapping row for the same category as line 2; skipped so it is not double counted

MAPPED FILE EXISTS: True
Mapped clause count: 32
First mapped record:
{"clause_id": "indian_aera_rfp_consultant_2025__Confidentiality__0", "contract_id": "indian_aera_rfp_consultant_2025", "cuad_category": "INDIAN_SET", "clausexplain_category": "Confidentiality", "clause_text": "Confidentiality The Consultant and its Key Personnel shall not, either during the term or within one year after the expiration or termination of this Agreement disclose any proprietary information, including information relating to reports, data, drawings, design software or other material, whether written or oral, in electronic or magnetic format, and the contents thereof; and any reports, digests or summaries created or derived from any of the foregoing that is provided by the Authority to the Consultant, its Key Personnel; any information provided by or relating to the Authority, its technology, technical processes, business affairs or finances or any information relating to the Authority\u2019s employees, officers or other professionals or suppliers, customers, or contractors of the Authority; and any other information which the Consultant is under an obligation to keep confidential in relation to the Project, the Services or this Agreement (\"Confidential Information\"), without the prior written consent of the Authority.\n\nNotwithstanding the aforesaid, the Consultant, its Key Personnel or either of them may disclose, with prior written approval of the Authority, Confidential Information to the extent that such Confidential Information:\n\na) was in the public domain prior to its delivery to the Consultant, its Key Personnel or becomes a part of the public knowledge from a source other than the Consultant, its Key Personnel;\n\nb) was obtained from a third party with no known duty to maintain its confidentiality;\n\nc) is required to be disclosed by Applicable Laws or judicial or administrative or arbitral process or by any governmental instrumentalities, provided that for any such disclosure, the Consultant, its Key Personnel shall give the Authority, prompt written notice, and use reasonable efforts to ensure that such disclosure is accorded confidential treatment; and\n\nd) is provided to the professional advisers, agents, auditors or representatives of the Consultant or its Key Personnel, as is reasonable under the circumstances; provided, however, that the Consultant or Key Personnel, as the case may be, shall require their professional advisers, agents, auditors or its representatives, to undertake in writing to keep such Confidential Information, confidential and shall use its best efforts to ensure compliance with such undertaking.\n\nSubject to the confidentiality obligations above, the Consultant shall be allowed to use this engagement as an experience citation with other clients.", "char_start": 100239, "char_end": 102762, "category_status": "MAPPED", "source": "indian_set", "source_note": "AERA agreement; Confidentiality section"}

In [55]:
from pathlib import Path
import json

INDIAN = Path("/kaggle/working/indian_eval_project/indian_set")
mapped_path = INDIAN / "built_expanded" / "indian_mapped.jsonl"

mapped = [
    json.loads(line)
    for line in mapped_path.read_text(encoding="utf-8").splitlines()
    if line.strip()
]

for row in mapped:
    if any(term in row["contract_id"].lower() for term in ["dot", "stqc"]):
        print(
            row["contract_id"],
            "|", row["clausexplain_category"],
            "|", row["char_start"], row["char_end"],
            "|", row["source_note"]
        )

indian_dot_unified_licence_agreement | Indemnification | 72476 72859 | Licensor indemnity
indian_dot_unified_licence_agreement | Indemnification | 23566 24052 | Licensee indemnifies the licensor
indian_dot_unified_licence_agreement | Assignment | 24227 25691 | Transfer and assignment of licence agreement
indian_stqc_non_disclosure_agreement | Confidentiality | 2742 3777 | Definition of confidential information
indian_dot_unified_licence_agreement | Confidentiality | 83925 84150 | Duty to maintain secrecy
indian_dot_unified_licence_agreement | Penalties | 241861 242081 | Calculation of liquidated damages
indian_dot_unified_licence_agreement | Penalties | 68604 69254 | Penalty for failure to define service scope
indian_stqc_non_disclosure_agreement | Non-Solicitation | 12338 12770 | Restriction on soliciting employees and consultants
indian_stqc_non_disclosure_agreement | Confidentiality | 9537 9695 | Restriction on unauthorised disclosure
indian_stqc_non_disclosure_agreement | Penalties | 8525 9219 | Damages and litigation costs after breach

In [56]:
from collections import Counter

print("Mapped clauses:", len(mapped))

print("\nCategory counts:")
for category, count in sorted(
    Counter(row["clausexplain_category"] for row in mapped).items()
):
    print(f"{category}: {count}")

print("\nTarget clauses:")
for row in mapped:
    if (
        row["source_note"] in [
            "Licensee indemnifies the licensor",
            "Restriction on soliciting employees and consultants",
        ]
    ):
        print(
            row["clausexplain_category"],
            "|", row["source_note"],
            "|", len(row["clause_text"]), "characters"
        )

Mapped clauses: 32

Category counts:
Assignment: 1
Commercial Terms: 1
Confidentiality: 9
Force Majeure: 5
Indemnification: 6
Non-Solicitation: 1
Penalties: 9

Target clauses:
Indemnification | Licensee indemnifies the licensor | 486 characters
Non-Solicitation | Restriction on soliciting employees and consultants | 432 characters

In [57]:
import os
import sys
import subprocess
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"

env = os.environ.copy()
env["PYTHONPATH"] = (
    str(WORK) + os.pathsep +
    str(INDIAN) + os.pathsep +
    env.get("PYTHONPATH", "")
)

cmd = [
    sys.executable,
    str(INDIAN / "eval_indian.py"),
    "--run_dir", str(WORK),
    "--fold", "0",
    "--ckpt", str(WORK / "ckpt_joint_cls_span_fold0.pt"),
    "--indian_dir", str(INDIAN / "built_expanded"),
    "--mapped_jsonl", str(WORK / "clauses_mapped.jsonl"),
    "--cuad_json", str(WORK / "CUAD_v1.json"),
    "--rules", str(WORK / "indian_legal_rules.csv"),
]

result = subprocess.run(
    cmd,
    env=env,
    capture_output=True,
    text=True,
    cwd=str(WORK)
)

print("Return code:", result.returncode)
print("\nSTDOUT:\n", result.stdout[-15000:])
print("\nSTDERR:\n", result.stderr[-5000:])

Return code: 0

STDOUT:
 32 Indian clauses: 12 in categories the model was trained on, 20 in categories it never saw
# Indian-context evaluation

32 clauses: 12 in categories seen in training, 20 in unseen categories. Small sample: read gaps, not decimals.

## Category classification (seen categories only)

| Model | n | accuracy | 95% interval | macro-F1 |
|---|---|---|---|---|
| ClauseXplain checkpoint | 12 | 0.500 | 0.254 to 0.746 | 0.436 |
| majority (trained on CUAD fold 0) | 12 | 0.000 |  | 0.000 |
| tfidf_logreg (trained on CUAD fold 0) | 12 | 0.417 | 0.193 to 0.680 | 0.422 |

## Span localisation (windowed)

| Method | n | token-F1 | exact match | IoU |
|---|---|---|---|---|
| span head (best-match gold) | 12 | 0.583 | 0.000 | 0.502 |
| span head (own label) | 12 | 0.583 | 0.000 | 0.502 |
| random span | 12 | 0.177 | 0.000 | 0.117 |
| whole_window_baseline | 12 | 0.325 | 0.000 | 0.204 |
| lexical_centroid_baseline | 12 | 0.484 | 0.000 | 0.407 |

## Categories the model never saw: what it predicted instead

| True category | predictions |
|---|---|
| Confidentiality | Other x7, Termination x1, Intellectual Property x1 |
| Force Majeure | Liability x4, Termination x1 |
| Indemnification | Liability x4, Intellectual Property x1, Other x1 |

## Rule-layer findings (see indian_rule_flags.csv)

- ICA_S124_01:none: 3
- ICA_S124_01:possible: 3
- ICA_S27_02:possible: 1
- ICA_S74_01:flag: 3
- ICA_S74_01:none: 6



STDERR:
 Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/269 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 269/269 [00:00<00:00, 9021.74it/s]
[transformers] LongformerModel LOAD REPORT from: allenai/longformer-base-4096
Key                            | Status     |  |
-------------------------------+------------+--+-
lm_head.layer_norm.weight      | UNEXPECTED |  |
lm_head.dense.bias             | UNEXPECTED |  |
longformer.pooler.dense.bias   | UNEXPECTED |  |
lm_head.layer_norm.bias        | UNEXPECTED |  |
longformer.pooler.dense.weight | UNEXPECTED |  |
lm_head.decoder.weight         | UNEXPECTED |  |
lm_head.bias                   | UNEXPECTED |  |
lm_head.dense.weight           | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [58]:
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
INDIAN = WORK / "indian_set"
OUT = INDIAN / "built_expanded"

print("Evaluation output files:")
for path in sorted(OUT.iterdir()):
    print(path.name, f"({path.stat().st_size:,} bytes)")

Evaluation output files:
build_report.md (1,685 bytes)
indian_contracts.json (1,790,787 bytes)
indian_eval.json (7,620 bytes)
indian_eval.md (1,316 bytes)
indian_mapped.jsonl (39,383 bytes)
indian_rule_flags.csv (3,915 bytes)

In [69]:
import json
from pathlib import Path

WORK = Path("/kaggle/working/indian_eval_project")
eval_path = WORK / "indian_set" / "built_expanded" / "indian_eval.json"

with open(eval_path, "r", encoding="utf-8") as f:
    results = json.load(f)

print("Top-level keys:")
print(list(results.keys()))

print("\nEvaluation summary:")
for key, value in results.items():
    if isinstance(value, (str, int, float, bool)) or value is None:
        print(f"{key}: {value}")
    elif isinstance(value, dict):
        print(f"{key}: dictionary with keys {list(value.keys())[:15]}")
    elif isinstance(value, list):
        print(f"{key}: list with {len(value)} items")
        if value and isinstance(value[0], dict):
            print("  First item's keys:", list(value[0].keys()))
            print("  First item:", json.dumps(value[0], indent=2)[:1800])

Top-level keys:
['n_total', 'n_seen', 'n_unseen', 'cls', 'cls_acc_ci95', 'span', 'span_own_label', 'span_random_baseline', 'baselines_cls', 'tfidf_acc_ci95', 'baselines_span', 'unseen_category_predictions', 'rule_status_counts']

Evaluation summary:
n_total: 33
n_seen: 12
n_unseen: 21
cls: dictionary with keys ['n', 'accuracy', 'micro_f1', 'macro_f1', 'macro_f1_n_classes', 'per_class']
cls_acc_ci95: list with 2 items
span: dictionary with keys ['n', 'token_f1', 'exact_match', 'iou', 'n_truncated_no_gold']
span_own_label: dictionary with keys ['n', 'token_f1', 'exact_match', 'iou']
span_random_baseline: dictionary with keys ['n', 'token_f1', 'exact_match', 'iou']
baselines_cls: dictionary with keys ['majority', 'tfidf_logreg']
tfidf_acc_ci95: list with 2 items
baselines_span: dictionary with keys ['whole_window_baseline', 'lexical_centroid_baseline']
unseen_category_predictions: dictionary with keys ['Confidentiality', 'Indemnification', 'Force Majeure']
rule_status_counts: dictionary with keys ['ICA_S124_01:none', 'ICA_S124_01:possible', 'ICA_S27_02:possible', 'ICA_S74_01:flag', 'ICA_S74_01:none']

In [70]:
import json
from pathlib import Path
import pandas as pd

WORK = Path("/kaggle/working/indian_eval_project")
eval_path = WORK / "indian_set" / "built_expanded" / "indian_eval.json"

with open(eval_path, "r", encoding="utf-8") as f:
    results = json.load(f)

print("PER-CLASS CLASSIFICATION METRICS")
display(pd.DataFrame(results["cls"]["per_class"]).T)

print("\nSPAN METRICS")
print(json.dumps(results["span"], indent=2))

print("\nBASELINE CLASSIFICATION METRICS")
print(json.dumps(results["baselines_cls"], indent=2))

PER-CLASS CLASSIFICATION METRICS

                              precision    recall        f1  support
Assignment                          1.0  1.000000  1.000000      1.0
Commercial Terms                    0.0  0.000000  0.000000      1.0
Dispute Resolution                  NaN       NaN       NaN      0.0
Governing Law / Jurisdiction        NaN       NaN       NaN      0.0
Intellectual Property               NaN       NaN       NaN      0.0
Liability                           NaN       NaN       NaN      0.0
Non-Compete                         NaN       NaN       NaN      0.0
Non-Solicitation                    1.0  1.000000  1.000000      1.0
Other                               NaN       NaN       NaN      0.0
Penalties                           1.0  0.444444  0.615385      9.0
Termination                         NaN       NaN       NaN      0.0
Warranty                            NaN       NaN       NaN      0.0
Confidentiality                     NaN       NaN       NaN      0.0
Force Majeure                       NaN       NaN       NaN      0.0
Indemnification                     NaN       NaN       NaN      0.0
Modification                        NaN       NaN       NaN      0.0
Payment                             NaN       NaN       NaN      0.0
Privacy / Data Protection           NaN       NaN       NaN      0.0

SPAN METRICS
{
  "n": 12,
  "token_f1": 0.5831019685273903,
  "exact_match": 0.0,
  "iou": 0.5019278007430243,
  "n_truncated_no_gold": 0
}

BASELINE CLASSIFICATION METRICS
{
  "majority": {
    "n": 12,
    "accuracy": 0.0,
    "micro_f1": 0.0,
    "macro_f1": 0.0,
    "macro_f1_n_classes": 5,
    "per_class": {
      "Assignment": {
        "precision": 0.0,
        "recall": 0.0,
        "f1": 0.0,
        "support": 1
      },
      "Commercial Terms": {
        "precision": 0.0,
        "recall": 0.0,
        "f1": 0.0,
        "support": 1
      },
      "Dispute Resolution": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Governing Law / Jurisdiction": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Intellectual Property": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Liability": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Non-Compete": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Non-Solicitation": {
        "precision": 0.0,
        "recall": 0.0,
        "f1": 0.0,
        "support": 1
      },
      "Other": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Penalties": {
        "precision": 0.0,
        "recall": 0.0,
        "f1": 0.0,
        "support": 9
      },
      "Termination": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Warranty": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Confidentiality": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Force Majeure": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Indemnification": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Modification": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Payment": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Privacy / Data Protection": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      }
    }
  },
  "tfidf_logreg": {
    "n": 12,
    "accuracy": 0.4166666666666667,
    "micro_f1": 0.4166666666666667,
    "macro_f1": 0.4217171717171717,
    "macro_f1_n_classes": 6,
    "per_class": {
      "Assignment": {
        "precision": 0.5,
        "recall": 1.0,
        "f1": 0.6666666666666666,
        "support": 1
      },
      "Commercial Terms": {
        "precision": 0.3333333333333333,
        "recall": 1.0,
        "f1": 0.5,
        "support": 1
      },
      "Dispute Resolution": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Governing Law / Jurisdiction": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Intellectual Property": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Liability": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Non-Compete": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Non-Solicitation": {
        "precision": 1.0,
        "recall": 1.0,
        "f1": 1.0,
        "support": 1
      },
      "Other": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Penalties": {
        "precision": 1.0,
        "recall": 0.2222222222222222,
        "f1": 0.36363636363636365,
        "support": 9
      },
      "Termination": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Warranty": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Confidentiality": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Force Majeure": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Indemnification": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Modification": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Payment": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      },
      "Privacy / Data Protection": {
        "precision": NaN,
        "recall": NaN,
        "f1": NaN,
        "support": 0
      }
    }
  }
}